In [1]:
import numpy as np    
import pandas as pd

In [2]:
ktm=pd.read_csv('lalpurja_house_kathmandu_fixed.csv')
lat=pd.read_csv('lalpurja_house_lalitpur_fixed.csv')
bkt=pd.read_csv('lalpurja_house_bhaktapur_fixed.csv')

In [3]:
pd.set_option('display.max_columns',None)

In [4]:
ktm.sample(4)

,url,source,category,district,property_id,title,total_price_raw,property_type,property_face,year_built,road_type,negotiable,furnishing,city_area,pricing_raw,purpose,property_area,built_up_area,road_access,dimension,date_posted,views,municipality,ward_no,ring_road,landmark,hospital,airport,pharmacy,bhatbhateni,school,college,gym,public_transport,police_station,pashupatinath,boudhanath,atm,hotel,restaurant,banquet,ward_office,neighborhood
539,https://lalpurjanepal.com.np/properties/house-...,lalpurja,house,Kathmandu,6520,Property Details,4 Crore,Semi-commercial,North-East,NaN,Blacktopped,Yes,NaN,"Kathmandu, Kapan",4 Crore,Sale,4 Aana,1213 square-feet,20 Feet,F 32 Feet,2025 May 15,121.0,Budhanilkanta,10,3km,Kapan | Shivamandir,1km,5km,200m,4km,200m,300m,200m,200m,1.5km,5km,5km,150m,200m,300m,150m,800m,Kapan
999,https://lalpurjanepal.com.np/properties/house-...,lalpurja,house,Kathmandu,4475,Property Details,5 Crore 75 Lakh,Residential,South-East,2079,Blacktopped,Yes,Semi Furnished,"Kathmandu, Shantinagar",5 Crore 75 Lakh,Sale,4.5 Aana,3.5 square-feet,13 Feet,F 30 Feet,2024 December 31,438.0,Kathmandu,31,100m,Om Kareshwor,500m,500m,100m,100m,100m,100m,100m,100m,100m,1km,2km,100m,100m,NaN,NaN,300m,Shantinagar
1189,https://lalpurjanepal.com.np/properties/house-...,lalpurja,house,Kathmandu,3721,Property Details,8 crore 90 lakh,Residential,South,NaN,Blacktopped,No,Full Furnished,"Kathmandu, Budhanilkantha",8 crore 90 lakh,Sale,12.75 Aana,5 aana,18 Feet,NaN,2024 November 24,204.0,Budhanilkantha,NaN,5km,Rudreshwor Chowk | Bajeko Sekuwa,Neuro hospital,7km,100m,3km,100m,100m,100m,10m,100m,6km,4km,100m,200m,50m,50m,100m,Budhanilkantha
1247,https://lalpurjanepal.com.np/properties/house-...,lalpurja,house,Kathmandu,3442,Property Details,5 Crore 50 Lakh,Residential,East,2070,Blacktopped,Yes,Semi Furnished,"Kathmandu, Samakhusi",5 Crore 50 Lakh,Sale,6.5 Aana,5.5 aana,20 Feet,F 50 ft,2024 November 11,309.0,NaN,NaN,NaN,Mahadev Tar Mandir,2 km,NaN,100 m,1 km,NaN,NaN,NaN,200 m,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Samakhusi

In [5]:
lat.sample(4)

,url,source,category,district,property_id,title,total_price_raw,property_type,property_face,year_built,road_type,negotiable,furnishing,city_area,pricing_raw,purpose,property_area,built_up_area,road_access,dimension,date_posted,views,municipality,ward_no,ring_road,landmark,hospital,airport,pharmacy,bhatbhateni,school,college,gym,public_transport,police_station,pashupatinath,boudhanath,atm,hotel,restaurant,banquet,ward_office,neighborhood
39,https://lalpurjanepal.com.np/properties/house-...,lalpurja,house,Lalitpur,8218,Property Details,8 Crore 25 Lakh,Residential,South-East,2069,Blacktopped,Yes,Semi Furnished,"Lalitpur, Dholahiti",8 Crore 25 Lakh,Sale,10 Aana,1369 square-feet,20 Feet,F 40 Feet,2025 August 26,183,Lalitpur,26,3km,Dolahiti | Ullens School,200m,10mm,300m,400m,200m,300m,300m,100m,450m,14km,18km,200m,150m,250m,400m,450m,Dholahiti
105,https://lalpurjanepal.com.np/properties/house-...,lalpurja,house,Lalitpur,7392,Property Details,4 Crore,Residential,North-West,2023,Paved,Yes,Semi Furnished,"Lalitpur, Bhaisepati",4 Crore,Sale,4.5 Aana,NaN,13 Feet,NaN,2025 July 2,369,Lalitpur,25,2.5km,Bhaisepati | Panchakanya Tole,Nepal Mediciti Hospital - 2km,10km,NaN,Pulchowk - 5km,Gyanodaya Bal Batika School - 3km,NaN,NaN,500m,600m,11km,13km,NaN,NaN,NaN,NaN,700m,Bhaisepati
403,https://lalpurjanepal.com.np/properties/house-...,lalpurja,house,Lalitpur,4080,Property Details,3 Crore 70 Lakh,Residential,West,2024,Blacktopped,Yes,Semi Furnished,"Lalitpur, Dholahiti",3 Crore 70 Lakh,Sale,4.2 Aana,3 aana,13 Feet,32,2024 December 12,287,lalitpur,14,1km,Osis School,1km,6km,NaN,NaN,100m,NaN,100m,50m,100m,NaN,NaN,NaN,NaN,NaN,NaN,100m,Dholahiti
305,https://lalpurjanepal.com.np/properties/house-...,lalpurja,house,Lalitpur,4969,Property Details,3 Crore 50 Lakh,Residential,South,2024,Paved,Yes,Semi Furnished,"Lalitpur, Tikathali",3 Crore 50 Lakh,Sale,4.1 Aana,1369 square-feet,20 Feet,NaN,2025 January 24,142,Lalitpur,05,100m,Pawan Prakriti School,100m,4.7km,100m,3.4km,100m,200m,100m,100m,200m,6km,10km,100m,1km,100m,1km,200m,Tikathali

In [6]:
bkt.sample(4)

,url,source,category,district,property_id,title,total_price_raw,property_type,property_face,year_built,road_type,negotiable,furnishing,city_area,pricing_raw,purpose,property_area,built_up_area,road_access,dimension,date_posted,views,municipality,ward_no,ring_road,landmark,hospital,airport,pharmacy,bhatbhateni,school,college,gym,public_transport,police_station,pashupatinath,boudhanath,atm,hotel,restaurant,banquet,ward_office,neighborhood
122,https://lalpurjanepal.com.np/properties/35-aan...,lalpurja,house,Bhaktapur,5109,Property Details,40 Lakh Per Aana,Residential,South-East,NaN,Gravelled,Yes,NaN,"Bhaktapur, Katunje",40 Lakh Per Aana,Sale,3.56 Aana,NaN,20 Feet,F 25 Feet,2025 February 4,280,Suryabinayak,5.0,5.5km,Sushila Bhairab Temple,500m,8km,300m,700m,300m,300m,NaN,300m,NaN,9km,10km,NaN,NaN,NaN,NaN,500m,Katunje
128,https://lalpurjanepal.com.np/properties/beauti...,lalpurja,house,Bhaktapur,4909,Property Details,2 Crore 80 Lakh,Residential,South-East,2022,Paved,Yes,NaN,"Bhaktapur, Suryabinayak",2 Crore 80 Lakh,Sale,4 Aana,960 square-feet,13 Feet,F 37 Feet,2025 January 21,280,Suryavinayak,8.0,10km,Suryabinayak Ganesh Temple,1.5km,12km,100m,4.2km,200m,NaN,NaN,100m,NaN,13km,14km,NaN,NaN,NaN,NaN,2km,Suryabinayak
183,https://lalpurjanepal.com.np/properties/house-...,lalpurja,house,Bhaktapur,2679,Property Details,3 Crore 70 Lakh,Residential,South-East,NaN,Soil Stabilized,Yes,Unfurnished,"Bhaktapur, Radhe Radhe",3 Crore 70 Lakh,Sale,3.2 Aana,3.2 aana,26 Feet,NaN,2024 August 29,435,NaN,NaN,NaN,NaN,200m,8.1km,100m,400m,200m,200m,NaN,200m,200m,9km,NaN,200m,200m,250m,250m,NaN,Radhe Radhe
172,https://lalpurjanepal.com.np/properties/5-aana...,lalpurja,house,Bhaktapur,3222,Property Details,3 Crore 90 Lakh,Residential,South-East,2079,Gravelled,No,Semi Furnished,"Bhaktapur, Radhe Radhe",3 Crore 90 Lakh,Sale,5.13 Aana,3902 square-feet,13 Feet,NaN,2024 October 23,480,Madhyapur Thimi,9.0,4 km,Nikosera Planning,2 km,9.1 km,400 m,900 m,400 m,1.8 km,400 m,200 m,1 km,8.9 km,9.7 km,300 m,400 m,300 m,400 m,2 km,Radhe Radhe

In [7]:
ktm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1605 entries, 0 to 1604
Data columns (total 43 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   url               1605 non-null   object
 1   source            1605 non-null   object
 2   category          1605 non-null   object
 3   district          1605 non-null   object
 4   property_id       1605 non-null   int64
 5   title             1599 non-null   object
 6   total_price_raw   1604 non-null   object
 7   property_type     1604 non-null   object
 8   property_face     1513 non-null   object
 9   year_built        1214 non-null   object
 10  road_type         1592 non-null   object
 11  negotiable        1604 non-null   object
 12  furnishing        1305 non-null   object
 13  city_area         1604 non-null   object
 14  pricing_raw       1604 non-null   object
 15  purpose           1604 non-null   object
 16  property_area     1604 non-null   object
 17  built_up_area     1163 non-null   object
 18  road_access       1595 non-null   object
 19  dimension         604 non-null    object
 20  date_posted       1604 non-null   object
 21  views             1604 non-null   float64
 22  municipality      1295 non-null   object
 23  ward_no           1267 non-null   object
 24  ring_road         1051 non-null   object
 25  landmark          1569 non-null   object
 26  hospital          1353 non-null   object
 27  airport           1365 non-null   object
 28  pharmacy          1137 non-null   object
 29  bhatbhateni       1083 non-null   object
 30  school            1249 non-null   object
 31  college           1041 non-null   object
 32  gym               896 non-null    object
 33  public_transport  1350 non-null   object
 34  police_station    987 non-null    object
 35  pashupatinath     1335 non-null   object
 36  boudhanath        1299 non-null   object
 37  atm               852 non-null    object
 38  hotel             838 non-null    object
 39  restaurant        841 non-null    object
 40  banquet           809 non-null    object
 41  ward_office       1239 non-null   object
 42  neighborhood      1602 non-null   object
dtypes: float64(1), int64(1), object(41)
memory usage: 539.3+ KB

In [8]:
ktm.columns.to_list()

['url',
 'source',
 'category',
 'district',
 'property_id',
 'title',
 'total_price_raw',
 'property_type',
 'property_face',
 'year_built',
 'road_type',
 'negotiable',
 'furnishing',
 'city_area',
 'pricing_raw',
 'purpose',
 'property_area',
 'built_up_area',
 'road_access',
 'dimension',
 'date_posted',
 'views',
 'municipality',
 'ward_no',
 'ring_road',
 'landmark',
 'hospital',
 'airport',
 'pharmacy',
 'bhatbhateni',
 'school',
 'college',
 'gym',
 'public_transport',
 'police_station',
 'pashupatinath',
 'boudhanath',
 'atm',
 'hotel',
 'restaurant',
 'banquet',
 'ward_office',
 'neighborhood']

In [9]:
# 1. Define the specific categorical columns from your data
categorical_cols = [
    'district', 'property_type', 'property_face', 'road_type', 
    'municipality', 'ward_no', 'neighborhood', 'purpose'
]

# 2. Run the Analysis Loop
print("🚀 --- CATEGORICAL VALUE COUNTS ANALYSIS --- 🚀\n")

for col in categorical_cols:
    if col in ktm.columns:
        print(f"🔹 COLUMN: {col.upper()}")
        print(f"Total Missing: {ktm[col].isnull().sum()}")
        print(f"Unique Labels: {ktm[col].nunique()}")
        print("-" * 35)
        
        # Displaying top 15 values for clarity
        print(ktm[col].value_counts().head(15))
        print("=" * 45 + "\n")
    else:
        print(f"⚠️ Column '{col}' not found in the dataset.\n")
        print('=====================================')

🚀 --- CATEGORICAL VALUE COUNTS ANALYSIS --- 🚀

🔹 COLUMN: DISTRICT
Total Missing: 0
Unique Labels: 1
-----------------------------------
district
Kathmandu    1605
Name: count, dtype: int64
=============================================

🔹 COLUMN: PROPERTY_TYPE
Total Missing: 1
Unique Labels: 3
-----------------------------------
property_type
Residential        1312
Commercial          175
Semi-commercial     117
Name: count, dtype: int64
=============================================

🔹 COLUMN: PROPERTY_FACE
Total Missing: 92
Unique Labels: 12
-----------------------------------
property_face
East          364
South         248
West          230
South-East    182
North         151
North-East    137
South-West    119
North-West     77
west            2
east            1
south-west      1
south-east      1
Name: count, dtype: int64
=============================================

🔹 COLUMN: ROAD_TYPE
Total Missing: 13
Unique Labels: 5
-----------------------------------
road_type
Blacktopped        960
Paved              229
Gravelled          169
Soil Stabilized    143
alley               91
Name: count, dtype: int64
=============================================

🔹 COLUMN: MUNICIPALITY
Total Missing: 310
Unique Labels: 81
-----------------------------------
municipality
Kathmandu              440
Budhanilkantha         227
Tokha                  112
Kageshwori Manohara     94
Budanilkantha           58
Nagarjun                46
Tarkeshwor              24
Budhanilakantha         22
Budhanilkanta           21
Chandragiri             19
Gokarneswor             18
Kageshwori Manahora     18
Kageswori Manohara      17
Gokarneshwor            16
Kirtipur                12
Name: count, dtype: int64
=============================================

🔹 COLUMN: WARD_NO
Total Missing: 338
Unique Labels: 47
-----------------------------------
ward_no
08    137
06    127
04    103
03     86
07     83
09     82
10     78
02     65
13     55
05     54
31     48
32     47
14     36
16     36
11     36
Name: count, dtype: int64
=============================================

🔹 COLUMN: NEIGHBORHOOD
Total Missing: 3
Unique Labels: 126
-----------------------------------
neighborhood
Budhanilkantha    290
Tokha             102
Gothatar           64
Kapan              59
Tarkeshwor         37
Kalanki            36
Jorpati            36
Mulpani            34
Bhangal            33
Raniban            32
Kadaghari          31
Baluwatar          31
Baneshwor          26
Sukedhara          26
Koteshwor          23
Name: count, dtype: int64
=============================================

🔹 COLUMN: PURPOSE
Total Missing: 1
Unique Labels: 1
-----------------------------------
purpose
Sale    1604
Name: count, dtype: int64
=============================================

In [10]:
# ─────────────────────────────────────────
# DEEP ANALYZE EACH FILE INDIVIDUALLY
# ─────────────────────────────────────────
for name, df in [('Kathmandu', ktm), ('Lalitpur', lat), ('Bhaktapur', bkt)]:
    print(f"\n{'='*50}")
    print(f"=== {name} ===")
    print(f"Shape: {df.shape}")

    print(f"\n--- total_price_raw ---")
    print(df['total_price_raw'].value_counts().head(8))

    print(f"\n--- built_up_area ---")
    print(df['built_up_area'].value_counts().head(8))

    print(f"\n--- property_area ---")
    print(df['property_area'].value_counts().head(8))

    print(f"\n--- year_built ---")
    print(df['year_built'].value_counts().head(8))

    print(f"\n--- furnishing ---")
    print(df['furnishing'].value_counts())

    print(f"\n--- property_type ---")
    print(df['property_type'].value_counts())

    print(f"\n--- road_type ---")
    print(df['road_type'].value_counts())

    print(f"\n--- ring_road ---")
    print(df['ring_road'].value_counts().head(8))

    print(f"\n--- hospital ---")
    print(df['hospital'].value_counts().head(5))

==================================================
=== Kathmandu ===
Shape: (1605, 43)

--- total_price_raw ---
total_price_raw
3 Crore 50 Lakh    64
4 Crore            46
2 Crore 80 Lakh    38
4 Crore 50 Lakh    38
5 Crore 50 Lakh    36
2 Crore 50 Lakh    34
6 Crore            33
3 Crore 25 Lakh    32
Name: count, dtype: int64

--- built_up_area ---
built_up_area
1369 square-feet       116
1026.75 square-feet    101
3 aana                  52
1711.25 square-feet     49
4 aana                  46
1197.87 square-feet     40
684.5 square-feet       30
3.5 aana                27
Name: count, dtype: int64

--- property_area ---
property_area
4 Aana      180
3 Aana      128
3.5 Aana    110
5 Aana      107
4.5 Aana     83
6 Aana       76
2.5 Aana     55
8 Aana       47
Name: count, dtype: int64

--- year_built ---
year_built
2081    117
2080     63
2024     56
2079     49
2082     47
2060     46
2078     45
2075     45
Name: count, dtype: int64

--- furnishing ---
furnishing
Semi Furnished    654
Unfurnished       441
Full Furnished    210
Name: count, dtype: int64

--- property_type ---
property_type
Residential        1312
Commercial          175
Semi-commercial     117
Name: count, dtype: int64

--- road_type ---
road_type
Blacktopped        960
Paved              229
Gravelled          169
Soil Stabilized    143
alley               91
Name: count, dtype: int64

--- ring_road ---
ring_road
2km     167
1km     113
3km      88
500m     66
4km      57
200m     53
100m     43
5km      42
Name: count, dtype: int64

--- hospital ---
hospital
1km     319
500m    226
200m     87
300m     72
2km      67
Name: count, dtype: int64

==================================================
=== Lalitpur ===
Shape: (539, 43)

--- total_price_raw ---
total_price_raw
2 Crore 75 Lakh    23
2 Crore 90 Lakh    20
2 Crore 50 Lakh    18
3 Crore            18
2 Crore 80 Lakh    18
4 Crore 50 Lakh    17
2 Crore 60 Lakh    17
3 Crore 75 Lakh    13
Name: count, dtype: int64

--- built_up_area ---
built_up_area
1026.75 square-feet     67
3 aana                  17
1369 square-feet        16
941.18 square-feet      15
855.62 square-feet      14
855.625 square-feet     12
3.5 aana                11
1197.875 square-feet    11
Name: count, dtype: int64

--- property_area ---
property_area
3 Aana       70
3.5 Aana     66
4 Aana       55
3.25 Aana    28
5 Aana       25
4.5 Aana     23
3.75 Aana    18
2.75 Aana    13
Name: count, dtype: int64

--- year_built ---
year_built
2024    194
2025     41
2082     31
2023     22
2081     20
2080     19
2022     17
2079     15
Name: count, dtype: int64

--- furnishing ---
furnishing
Semi Furnished    358
Full Furnished     87
Unfurnished        51
Name: count, dtype: int64

--- property_type ---
property_type
Residential        503
Commercial          22
Semi-commercial     14
Name: count, dtype: int64

--- road_type ---
road_type
Paved              364
Blacktopped        104
Gravelled           53
Soil Stabilized     16
alley                1
Name: count, dtype: int64

--- ring_road ---
ring_road
4km      96
100m     47
3km      39
2km      35
5km      24
2.5km    21
1km      16
1.5km    11
Name: count, dtype: int64

--- hospital ---
hospital
300m    98
200m    60
400m    55
100m    49
1km     36
Name: count, dtype: int64

==================================================
=== Bhaktapur ===
Shape: (184, 43)

--- total_price_raw ---
total_price_raw
1 Crore 80 Lakh    8
2 Crore 50 Lakh    7
2 Crore 40 Lakh    6
3 Crore            6
3 Crore 50 Lakh    6
2 Crore 20 Lakh    5
2 Crore 65 Lakh    5
2 Crore            5
Name: count, dtype: int64

--- built_up_area ---
built_up_area
1026.75 square-feet    6
1000 square-feet       3
1800 square-feet       3
700 square-feet        2
1550 square-feet       2
800 square-feet        2
2000 square-feet       2
918 square-feet        2
Name: count, dtype: int64

--- property_area ---
property_area
4 Aana       21
3 Aana       17
3.5 Aana     10
5 Aana        9
3.75 Aana     8
3.25 Aana     6
2.75 Aana     4
2.5 Aana      4
Name: count, dtype: int64

--- year_built ---
year_built
2078    20
2081    14
2076    13
2080    12
2074    10
2079    10
2075     9
2072     9
Name: count, dtype: int64

--- furnishing ---
furnishing
Semi Furnished    89
Unfurnished       45
Full Furnished    28
Name: count, dtype: int64

--- property_type ---
property_type
Residential        161
Commercial          15
Semi-commercial      8
Name: count, dtype: int64

--- road_type ---
road_type
Blacktopped        58
Gravelled          49
Paved              44
Soil Stabilized    32
alley               1
Name: count, dtype: int64

--- ring_road ---
ring_road
5km     13
3km     13
10km    11
12km    10
6km     10
4km     10
8km      6
7km      6
Name: count, dtype: int64

--- hospital ---
hospital
2km      30
1km      29
500m     20
1.5km    13
3km       8
Name: count, dtype: int64

In [11]:
# Assign district names — district column has coords like before
ktm['district'] = 'Kathmandu'
lat['district'] = 'Lalitpur'
bkt['district'] = 'Bhaktapur'

In [12]:
# Combine all three
df_lph = pd.concat([ktm, lat, bkt], ignore_index=True)

In [13]:
print(f"=== Combined Shape: {df_lph.shape} ===")
print(f"Kathmandu: {len(ktm)} rows")
print(f"Lalitpur:  {len(lat)} rows")
print(f"Bhaktapur: {len(bkt)} rows")
print(f"Districts: {df_lph['district'].value_counts().to_dict()}")

=== Combined Shape: (2328, 43) ===
Kathmandu: 1605 rows
Lalitpur:  539 rows
Bhaktapur: 184 rows
Districts: {'Kathmandu': 1605, 'Lalitpur': 539, 'Bhaktapur': 184}

In [14]:
# ─────────────────────────────────────────
# STEP 2 — DROP USELESS COLUMNS
# url — not useful for modeling
# source — all "lalpurja"
# property_id — just an ID
# title — all "Property Details"
# purpose — all "Sale"
# city_area — redundant with district/neighborhood
# category — all "house"
# landmark — 100% null
# ward_office — mostly null
# pricing_raw — redundant with total_price_raw
# ─────────────────────────────────────────
drop_cols = ['url', 'source', 'property_id', 'title',
             'purpose', 'city_area', 'category',
             'landmark', 'ward_office', 'pricing_raw']
df_lph.drop(columns=drop_cols, inplace=True)

In [15]:
print(f"\nAfter dropping useless columns: {df_lph.shape}")
print(f"Columns remaining: {list(df_lph.columns)}")

After dropping useless columns: (2328, 33)
Columns remaining: ['district', 'total_price_raw', 'property_type', 'property_face', 'year_built', 'road_type', 'negotiable', 'furnishing', 'property_area', 'built_up_area', 'road_access', 'dimension', 'date_posted', 'views', 'municipality', 'ward_no', 'ring_road', 'hospital', 'airport', 'pharmacy', 'bhatbhateni', 'school', 'college', 'gym', 'public_transport', 'police_station', 'pashupatinath', 'boudhanath', 'atm', 'hotel', 'restaurant', 'banquet', 'neighborhood']

In [16]:
# ─────────────────────────────────────────
# STEP 3 — PARSE total_price_raw → total_price (NPR)
# Format examples:
#   "3 Crore 50 Lakh" → 3×10,000,000 + 50×100,000 = 35,000,000
#   "4 Crore"         → 4×10,000,000 = 40,000,000
#   "75 Lakh"         → 75×100,000 = 7,500,000
# Why: ML model needs numeric values not strings
# ─────────────────────────────────────────

def parse_nepali_price(val):
    if pd.isna(val):
        return np.nan
    
    val = str(val).strip().lower()
    total = 0
    
    # Extract crore value if present
    # Example: "3 crore 50 lakh" → crore=3
    crore_match = re.search(r'(\d+\.?\d*)\s*crore', val)
    if crore_match:
        total += float(crore_match.group(1)) * 10_000_000
    
    # Extract lakh value if present
    # Example: "3 crore 50 lakh" → lakh=50
    lakh_match = re.search(r'(\d+\.?\d*)\s*lakh', val)
    if lakh_match:
        total += float(lakh_match.group(1)) * 100_000
    
    return total if total > 0 else np.nan

import re

df_lph['total_price'] = df_lph['total_price_raw'].apply(parse_nepali_price)

In [17]:
df_lph.sample(5)

,district,total_price_raw,property_type,property_face,year_built,road_type,negotiable,furnishing,property_area,built_up_area,road_access,dimension,date_posted,views,municipality,ward_no,ring_road,hospital,airport,pharmacy,bhatbhateni,school,college,gym,public_transport,police_station,pashupatinath,boudhanath,atm,hotel,restaurant,banquet,neighborhood,total_price
1396,Kathmandu,1 Crore 85 Lakh,Residential,East,NaN,Gravelled,Yes,Unfurnished,4 Aana,1369 square-feet,10 Feet,NaN,2024 September 20,823.0,Kritipur,02,NaN,NaN,13km,200m,NaN,NaN,NaN,NaN,NaN,NaN,12km,NaN,200m,200m,NaN,NaN,Kirtipur,18500000.0
1949,Lalitpur,2 Crore 45 Lakh,Residential,East,2024,Paved,Yes,Semi Furnished,3 Aana,855.625 square-feet,13 Feet,NaN,2025 January 6,236.0,Mahalaxmi,NaN,50m,200m,5km,50m,200m,100m,100m,100m,100m,200m,9km,12km,50m,100m,100m,200m,Tikathali,24500000.0
915,Kathmandu,3 Crore 25 Lakh,Residential,East,2022,Blacktopped,Yes,Semi Furnished,4.5 Aana,1197.88 square-feet,13 Feet,F 32 Feet,2025 January 19,223.0,Tarkeshwor,04,2km,1km,13km,50m,3km,500m,3km,1km,50m,1km,13km,14km,500m,1km,200m,1km,Tarkeshwor,32500000.0
1056,Kathmandu,3 Crore 30 Lakh,Residential,East,2066,Paved,Yes,Semi Furnished,3.75 Aana,3 aana,10 Feet,NaN,2024 December 20,185.0,Budhanilkantha,09,NaN,1km,4km,NaN,NaN,100m,NaN,NaN,100m,NaN,2km,3km,NaN,NaN,NaN,NaN,Sukedhara,33000000.0
1735,Lalitpur,7 Crore,Residential,South-West,2061,Blacktopped,Yes,Semi Furnished,9 Aana,NaN,13 Feet,NaN,2025 June 18,246.0,Lalitpur,03,150m,Alka Hospital - 1.5km,10km,NaN,Pulchowk - 2km,St. Xavier's School - 1.5km,NaN,NaN,150m,1.5km,8km,10km,NaN,NaN,NaN,NaN,Dhobighat,70000000.0

In [18]:
# Drop original raw column — no longer needed
df_lph.drop(columns=['total_price_raw'], inplace=True)

In [19]:
# Verify
print("=== total_price stats ===")
print(df_lph['total_price'].describe())
print(f"\nNulls: {df_lph['total_price'].isnull().sum()}")
print(f"\nSample values (NPR):")
print(df_lph['total_price'].value_counts().head(8))

=== total_price stats ===
count    2.325000e+03
mean     4.162662e+07
std      3.858779e+07
min      2.000000e+05
25%      2.500000e+07
50%      3.300000e+07
75%      4.700000e+07
max      9.000000e+08
Name: total_price, dtype: float64

Nulls: 3

Sample values (NPR):
total_price
35000000.0    85
40000000.0    61
45000000.0    61
28000000.0    61
25000000.0    60
32500000.0    53
30000000.0    49
27500000.0    48
Name: count, dtype: int64

In [20]:
# ─────────────────────────────────────────
# QUICK PRICE SANITY CHECK
# Min 200k is too cheap for a house
# Max 900M (9 Crore) is extremely high
# ─────────────────────────────────────────
print("=== Suspiciously cheap (below 5M) ===")
print(df_lph[df_lph['total_price'] < 5000000][['district', 'neighborhood', 'total_price', 'property_area']].head(10))

print("\n=== Suspiciously expensive (above 200M) ===")
print(df_lph[df_lph['total_price'] > 200000000][['district', 'neighborhood', 'total_price', 'property_area']].head(10))

print(f"\n=== Below 5M count: {(df_lph['total_price'] < 5000000).sum()} ===")
print(f"=== Above 200M count: {(df_lph['total_price'] > 200000000).sum()} ===")

=== Suspiciously cheap (below 5M) ===
      district    neighborhood  total_price property_area
1    Kathmandu      Banasthali    3500000.0     4.25 Aana
18   Kathmandu           Naxal     200000.0       16 Aana
60   Kathmandu         Thankot    2500000.0     9.31 Aana
66   Kathmandu  Budhanilkantha    4200000.0    11.18 Aana
76   Kathmandu           Dallu    3500000.0        4 Aana
179  Kathmandu  Budhanilkantha    4500000.0        6 Aana
241  Kathmandu           Tokha    3100000.0        4 Aana
312  Kathmandu        Gothatar    4800000.0        6 Aana
323  Kathmandu     Buddhanagar    2000000.0        7 Aana
326  Kathmandu       Maitidevi    1600000.0        2 Aana

=== Suspiciously expensive (above 200M) ===
       district    neighborhood  total_price property_area
50    Kathmandu  Budhanilkantha  225000000.0       32 Aana
431   Kathmandu            Ason  250000000.0  2000 Sq. Ft.
661   Kathmandu         Dhapasi  230000000.0       24 Aana
750   Kathmandu        New Road  220000000.0     2.75 Aana
846   Kathmandu  Budhanilkantha  265000000.0       29 Aana
940   Kathmandu          Boudha  300000000.0        8 Aana
969   Kathmandu        New Road  350000000.0      3.1 Aana
978   Kathmandu  Budhanilkantha  320000000.0    3.5 Ropani
1025  Kathmandu     Maharajgunj  900000000.0       72 Aana
1280  Kathmandu  Budhanilkantha  210000000.0       26 Aana

=== Below 5M count: 50 ===
=== Above 200M count: 17 ===

In [21]:
# ─────────────────────────────────────────
# FILTER PRICE RANGE
# Why below 10M: Houses in Kathmandu valley
# realistically cost minimum 10M NPR
# Anything below is likely a land listing
# or per-aana price that slipped through
# Why above 500M: Extremely rare, likely
# commercial mega properties not relevant
# for our residential housing model
# ─────────────────────────────────────────
before = len(df_lph)

df_lph = df_lph[
    (df_lph['total_price'] >= 10000000) &  # min 1 Crore
    (df_lph['total_price'] <= 500000000)   # max 50 Crore
].reset_index(drop=True)

print(f"Before filter: {before}")
print(f"After filter:  {len(df_lph)}")
print(f"Removed:       {before - len(df_lph)} rows")
print(f"\nprice range: {df_lph['total_price'].min():,.0f} – {df_lph['total_price'].max():,.0f}")

Before filter: 2328
After filter:  2190
Removed:       138 rows

price range: 10,000,000 – 350,000,000

In [22]:
pd.set_option('display.max_rows',None)

In [23]:
df_lph.sample(4)

,district,property_type,property_face,year_built,road_type,negotiable,furnishing,property_area,built_up_area,road_access,dimension,date_posted,views,municipality,ward_no,ring_road,hospital,airport,pharmacy,bhatbhateni,school,college,gym,public_transport,police_station,pashupatinath,boudhanath,atm,hotel,restaurant,banquet,neighborhood,total_price
1252,Kathmandu,Residential,South-East,NaN,Blacktopped,Yes,Semi Furnished,7 Aana,NaN,26 Feet,NaN,2024 October 1,246.0,NaN,NaN,NaN,200m,NaN,200m,NaN,250m,250m,few minutes walking distance,200m,few minutes walking distance,NaN,NaN,200m,200m,few minutes walking distance,few minutes walking distance,Raniban,65000000.0
398,Kathmandu,Commercial,North-East,2021,Paved,Yes,Semi Furnished,2000 Sq. Ft.,2000 square-feet,13 Feet,NaN,2025 June 12,236.0,Kathmandu,24,2km,700m to Bir Hospital,6.4km,59m,3.2km,500m to Shree Mahankal School,500m,300m,350m,100m,5.1km,6km,100m,250m,250m,500m,Ason,250000000.0
1183,Kathmandu,Semi-commercial,East,NaN,Blacktopped,Yes,Semi Furnished,26 Aana,6 aana,14 Feet,NaN,2024 October 27,702.0,NaN,NaN,NaN,400m,12km,300m,NaN,200m,200m,few minutes walking distance,250m,few minutes walking distance,12.5km,NaN,200m,250m,500m,few minutes walking distance,Budhanilkantha,210000000.0
630,Kathmandu,Residential,North-East,2050,Blacktopped,Yes,Unfurnished,18 Aana,1500 square-feet,13 Feet,F 40 Feet,2025 March 31,310.0,Kathmandu,14,1km,1km,7km,200m,2km,500m,500m,200m,200m,200m,7km,7km,200m,1km,200m,500m,Kalimati,190000000.0

In [24]:
df=df_lph.copy()

In [25]:
# ─────────────────────────────────────────
# STEP 4 — PARSE property_area → land_size_aana
# Keeping original property_area column for safety
# Will drop at the end after full verification
# ─────────────────────────────────────────

def parse_property_area(val):
    if pd.isna(val):
        return np.nan

    val = str(val).strip().lower()

    # If no number found → garbage value like "Lalitpur, Balkumari"
    num_match = re.search(r'(\d+\.?\d*)', val)
    if not num_match:
        return np.nan
    num = float(num_match.group(1))

    if 'aana' in val or 'anna' in val:
        # Standard unit — return directly
        return num
    elif 'ropani' in val:
        # 1 ropani = 16 aana
        # Example: "1 Ropani" → 16, "3.5 Ropani" → 56
        return num * 16
    elif 'paisa' in val:
        # 4 paisa = 1 aana
        # Example: "3 Paisa" → 0.75 aana
        return round(num / 4, 3)
    elif 'daam' in val:
        # 16 daam = 1 aana
        # Example: "4.06 Daam" → 0.25 aana
        return round(num / 16, 3)
    elif 'sq. meter' in val or 'sq meter' in val:
        # 1 aana = 31.8 sqm
        # Example: "291.55 Sq. Meter" → 9.17 aana
        return round(num / 31.8, 2)
    elif 'sq' in val or 'feet' in val or 'ft' in val:
        # 1 aana = 342.25 sqft
        # Example: "2000 Sq. Ft." → 5.84 aana
        return round(num / 342.25, 2)

    return np.nan

# Create new column — keep original property_area intact
df_lph['land_size_aana'] = df_lph['property_area'].apply(parse_property_area)

# Verify
print("=== land_size_aana stats ===")
print(df_lph['land_size_aana'].describe())
print(f"\nNulls: {df_lph['land_size_aana'].isnull().sum()}")
print(f"Below 1 aana:  {(df_lph['land_size_aana'] < 1).sum()}")
print(f"Above 50 aana: {(df_lph['land_size_aana'] > 50).sum()}")
print(f"\nSample values:")
print(df_lph['land_size_aana'].value_counts().head(10))

=== land_size_aana stats ===
count    2189.000000
mean        5.245304
std         6.455563
min         0.000000
25%         3.250000
50%         4.000000
75%         5.500000
max       216.000000
Name: land_size_aana, dtype: float64

Nulls: 1
Below 1 aana:  19
Above 50 aana: 4

Sample values:
land_size_aana
4.00    244
3.00    213
3.50    183
5.00    136
4.50    106
6.00     82
2.50     69
3.75     64
3.25     61
8.00     48
Name: count, dtype: int64

In [26]:
df_lph.sample(4)

,district,property_type,property_face,year_built,road_type,negotiable,furnishing,property_area,built_up_area,road_access,dimension,date_posted,views,municipality,ward_no,ring_road,hospital,airport,pharmacy,bhatbhateni,school,college,gym,public_transport,police_station,pashupatinath,boudhanath,atm,hotel,restaurant,banquet,neighborhood,total_price,land_size_aana
1204,Kathmandu,Residential,North-East,2080,Blacktopped,Yes,Semi Furnished,4 Aana,3.75 aana,12 Feet,F 44 Sq.ft,2024 October 21,282.0,Tokha,3,NaN,500 m,NaN,200m,1 Km,1m,NaN,NaN,300 m,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Tokha,31000000.0,4.00
753,Kathmandu,Residential,North-East,2078,Soil Stabilized,Yes,Full Furnished,6 Aana,1976.73 square-feet,12 Feet,F 30 Feet,2025 February 13,316.0,Gokarnashwor,04,4.2km,1.2km,6.5km,500m,4.5km,300m,1.2km,500m,550m,600m,4.5km,3.5km,500m,800m,500m,700m,Gokarneshwor,37500000.0,6.00
1518,Lalitpur,Residential,North-East,2078,Paved,Yes,Semi Furnished,3.75 Aana,1026.75 square-feet,16 Feet,F 52 Feet,2025 September 1,245.0,Mahalaxmi,01,1500m,400m,8km,100m,800m,100m,400m,100m,100m,400m,12km,16km,100m,100m,150m,200m,Imadol,41000000.0,3.75
23,Kathmandu,Commercial,South-West,2070,Blacktopped,Yes,NaN,6.5 Aana,2224.62 square-feet,21 Feet,F 50 Feet,2025 October 12,408.0,Kathmandu,16,2km,Chhetrapati Free Clinic - 200m,6.5 km,NaN,NaN,Precious National Academy Secondary School - 1...,College Nepal - 3km,NaN,600m,NaN,5km,7km,NaN,NaN,NaN,NaN,Chettrapati,200000000.0,6.50

In [27]:
df_lph['built_up_area'].value_counts()

built_up_area
1026.75 square-feet      173
1369 square-feet         124
3 aana                    67
4 aana                    53
1197.87 square-feet       52
1711.25 square-feet       49
3.5 aana                  38
684.5 square-feet         37
855.62 square-feet        36
1197.875 square-feet      34
5 aana                    31
855.625 square-feet       30
941.18 square-feet        26
2.5 aana                  24
3.75 aana                 19
1200 square-feet          15
900 square-feet           12
4.5 aana                  12
2 aana                    12
6 aana                    12
1540.12 square-feet       11
1283.43 square-feet       11
2053.5 square-feet        10
941.19 square-feet        10
2500 square-feet          10
1283.44 square-feet       10
3000 square-feet          10
1026 square-feet           9
1095.2 square-feet         9
1197.88 square-feet        9
2.75 aana                  9
2000 square-feet           9
2395.75 square-feet        9
1000 square-feet           9
1197.8 square-feet         8
2800 square-feet           8
850 square-feet            7
1197 square-feet           7
700 square-feet            7
2400 square-feet           7
941.1875 square-feet       7
855.6 square-feet          7
1800 square-feet           6
1540.125 square-feet       6
3.25 aana                  6
1112.31 square-feet        6
2738 square-feet           6
1850 square-feet           6
2200 square-feet           5
5000 square-feet           5
1882.375 square-feet       5
3500 square-feet           5
800 square-feet            5
3200 square-feet           5
2600 square-feet           5
2.2 aana                   5
8 aana                     5
1500 square-feet           5
950 square-feet            5
2150 square-feet           4
1300 square-feet           4
1900 square-feet           4
1700 square-feet           4
2100 square-feet           4
4000 square-feet           4
650 square-feet            4
2700 square-feet           4
750 square-feet            4
2300 square-feet           4
4.2 aana                   3
1550 square-feet           3
1050 square-feet           3
2350 square-feet           3
342.25 square-feet         3
1650 square-feet           3
1600 square-feet           3
1950 square-feet           3
3100 square-feet           3
787.17 square-feet         3
1368 square-feet           3
2450 square-feet           3
1750 square-feet           3
2900 square-feet           3
6.5 aana                   3
598.93 square-feet         3
925 square-feet            2
2689 square-feet           2
2.65 aana                  2
3755 square-feet           2
1026.75 aana               2
3080.25 square-feet        2
1129.42 square-feet        2
3246 square-feet           2
941.1875 aana              2
1100 square-feet           2
1035 square-feet           2
3422.5 square-feet         2
3.5 square-feet            2
684 square-feet            2
924.075 square-feet        2
256.68 square-feet         2
3764.75 square-feet        2
770.06 square-feet         2
7 aana                     2
4800 square-feet           2
2.25 aana                  2
839 square-feet            2
1454.56 square-feet        2
1163.64 square-feet        2
4200 square-feet           2
5.5 aana                   2
3.3 aana                   2
2.5 square-feet            2
2.6 aana                   2
1162 square-feet           2
2898.04 square-feet        2
4.75 aana                  2
5476 square-feet           2
889.85 square-feet         2
513.375 square-feet        2
427.81 square-feet         2
975.412 square-feet        2
1890 square-feet           2
793 square-feet            2
1540.13 square-feet        2
3150 square-feet           2
400 square-feet            2
500 square-feet            2
1400 square-feet           2
3400 square-feet           2
760 square-feet            2
918 square-feet            2
1112.313 square-feet       2
718.72 square-feet         2
1870 square-feet           1
4836 square-feet           1
2793.42 square-feet        1
119.22 square-feet         1
468.88 square-feet         1
1266.32 square-feet        1
1180.79 square-feet        1
3077.48 square-feet        1
2098 square-feet           1
139.09 square-meter        1
2501 square-feet           1
1368.88 square-feet        1
1369 aana                  1
1908 square-feet           1
1026.25 square-feet        1
3714.93 square-feet        1
57.6 square-feet           1
3784 square-feet           1
1969 square-feet           1
4275 square-feet           1
2731 square-feet           1
7580.23 square-feet        1
2826.05 square-feet        1
1996 square-feet           1
3935.87 square-feet        1
2798 square-feet           1
2033 square-feet           1
2389.65 square-feet        1
3217.76 square-feet        1
1090.814 square-feet       1
3080.95 square-feet        1
2486.65 square-feet        1
3468.73 square-feet        1
6160.5 square-feet         1
3336.93 square-feet        1
1213 square-feet           1
1864 square-feet           1
1882.3 square-feet         1
12 aana                    1
2286.84 square-feet        1
1202 square-feet           1
2551.5 square-feet         1
3457 square-feet           1
1123.6 square-feet         1
2012 square-feet           1
2338.56 square-feet        1
1.41 aana                  1
598.9 square-feet          1
1.75 aana                  1
2918.6 square-feet         1
956.66 square-feet         1
759.79 square-feet         1
1490 square-feet           1
855.6 aana                 1
3850 square-feet           1
3143 square-feet           1
1037 square-feet           1
1625.68 square-feet        1
2121 square-feet           1
1964.51 square-feet        1
1480.03 square-feet        1
1519.91 square-feet        1
995 square-feet            1
1540.1 square-feet         1
340 square-feet            1
701.92 square-feet         1
2125.12 square-feet        1
821.4 square-feet          1
2481.312 square-feet       1
895 square-feet            1
3 paisa                    1
5.75 aana                  1
1020 square-feet           1
1005.29 square-feet        1
1018 square-feet           1
1010 square-feet           1
2309 square-feet           1
1369                       1
1976.73 square-feet        1
1112.3125 aana             1
1406.65 square-feet        1
2909 square-feet           1
3600 square-feet           1
2042 square-feet           1
1579 square-feet           1
3300 square-feet           1
644 square-feet            1
2278 square-feet           1
2173 square-feet           1
651.71 square-feet         1
2929.21 square-feet        1
1454.5625 square-feet      1
1969.42 square-feet        1
3563 square-feet           1
2224.625 square-feet       1
855.63 square-feet         1
1897.89 square-feet        1
1825 square-feet           1
2365 square-feet           1
225 square-feet            1
1197.9 square-feet         1
4400 square-feet           1
682.5 square-feet          1
1883 square-feet           1
931.3 square-feet          1
4 square-feet              1
3.1 aana                   1
1280 square-feet           1
3250 square-feet           1
906.97 square-feet         1
4150 square-feet           1
760.46 square-feet         1
4.25 aana                  1
2.3 aana                   1
1130 square-feet           1
741 square-feet            1
1017 square-feet           1
4050 square-feet           1
3630 square-feet           1
6000 square-feet           1
1 aana                     1
1907.32 square-feet        1
1005 square-feet           1
1108.15 square-feet        1
791.5 square-feet          1
1063 square-feet           1
996 square-feet            1
1229.62 square-feet        1
1069.31 square-feet        1
2915 square-feet           1
2030.12 square-feet        1
85.56 square-feet          1
2928 square-feet           1
2059 square-feet           1
2250 square-feet           1
1484.36 square-feet        1
1705 square-feet           1
2156.38 square-feet        1
1755 square-feet           1
2413.5 square-feet         1
3406.66 square-feet        1
4991 square-feet           1
3800 square-feet           1
1898 square-feet           1
3550 square-feet           1
2093 square-feet           1
3140.5 square-feet         1
2625.99 square-feet        1
2224.62 square-feet        1
726 square-feet            1
1.05 aana                  1
3080 square-feet           1
3152 square-feet           1
1936.59 square-feet        1
2512 square-feet           1
2160 square-feet           1
2143 square-feet           1
2750 square-feet           1
4500 square-feet           1
2284 square-feet           1
2.8 aana                   1
3370 square-feet           1
801.4 square-feet          1
2719.43 square-feet        1
3488 square-feet           1
2110 square-feet           1
2124 square-feet           1
2051 square-feet           1
2026.17 square-feet        1
2650 square-feet           1
2532.19 square-feet        1
2491.37 square-feet        1
2108.89 square-feet        1
3.2 aana                   1
2626 square-feet           1
2407.73 square-feet        1
5.2 aana                   1
13 aana                    1
1450 square-feet           1
2447 square-feet           1
2347 square-feet           1
6800 square-feet           1
1.2 aana                   1
7.1 aana                   1
8.5 aana                   1
10000 square-feet          1
9100 square-feet           1
2456.57 square-feet        1
2215.26 square-feet        1
2716.69 square-feet        1
2366 square-feet           1
1868 square-feet           1
2.75 square-feet           1
2383 square-feet           1
1060.97 square-feet        1
2333.54 square-feet        1
2802 square-feet           1
2430 square-feet           1
2056 aana                  1
2120 square-feet           1
4449.25 square-feet        1
941.187 square-feet        1
1018.16 square-feet        1
671.48 square-feet         1
865.32 square-feet         1
1265.13 square-feet        1
2360 square-feet           1
2761 square-feet           1
752.95 square-feet         1
635.56 square-feet         1
4700.5 square-feet         1
821.27 square-feet         1
958.3 square-feet          1
703 square-feet            1
901.87 square-feet         1
2519.904 square-feet       1
2772.74 square-feet        1
2756.15 square-feet        1
3950 square-feet           1
2530.96 square-feet        1
2762 square-feet           1
2752.18 square-feet        1
1029 square-feet           1
1052 square-feet           1
547.6 square-feet          1
924.07 square-feet         1
1024 square-feet           1
739.26 square-feet         1
2850 square-feet           1
1129.4 square-feet         1
682 square-feet            1
881 square-feet            1
4791.5 square-feet         1
629 square-feet            1
1079.17 square-feet        1
1427 square-feet           1
1509.51 square-feet        1
470 square-feet            1
1409 square-feet           1
855.625 aana               1
1351.88 square-feet        1
770.0625 square-feet       1
680 square-feet            1
962.68 square-feet         1
652.58 square-feet         1
1345 square-feet           1
1539 square-feet           1
636.25 square-feet         1
762 square-feet            1
1283.4375 square-feet      1
1198 square-feet           1
795.36 square-feet         1
1710 square-feet           1
940 square-feet            1
1454.52 square-feet        1
840 square-feet            1
1175 square-feet           1
1350 square-feet           1
2426.08 square-feet        1
1041.3 square-feet         1
707.08 square-feet         1
895.13 square-feet         1
882 square-feet            1
748.5 square-feet          1
2635 square-feet           1
924.08 square-feet         1
832 square-feet            1
2.53 aana                  1
2.18 aana                  1
1.7 aana                   1
3.35 aana                  1
2170 square-feet           1
1163.65 square-feet        1
10 aana                    1
1.6 aana                   1
2.15 aana                  1
1366 square-feet           1
1135 square-feet           1
2.32 aana                  1
2.22 aana                  1
2.55 aana                  1
4.4 aana                   1
1219.57 square-feet        1
1030 square-feet           1
2550 square-feet           1
275 square-feet            1
600 square-feet            1
550 square-feet            1
684.25 square-feet         1
2125 square-feet           1
1380 square-feet           1
257 square-feet            1
8.25 aana                  1
980 square-feet            1
2017.17 square-feet        1
6500 square-feet           1
2399 square-feet           1
1820.63 square-feet        1
945.78 square-feet         1
3085.6 square-feet         1
3407 square-feet           1
3900 square-feet           1
2785.91 square-feet        1
1812 square-feet           1
4141 square-feet           1
1609.14 square-feet        1
2018.41 square-feet        1
3395.86 square-feet        1
216.825 square-feet        1
3849.27 square-feet        1
2507 square-feet           1
1870.8 square-feet         1
2016.78 square-feet        1
835 square-feet            1
2133.28 square-feet        1
2042.88 square-feet        1
2884.85 square-feet        1
1283 square-feet           1
1625 square-feet           1
789.13 square-feet         1
1962 square-feet           1
2804 square-feet           1
2736.54 square-feet        1
1307.39 square-feet        1
1782.71 square-feet        1
1212.2 square-feet         1
1190 square-feet           1
2770 square-feet           1
1909 square-feet           1
2854 square-feet           1
1454 square-feet           1
720 square-feet            1
698 square-feet            1
920 square-feet            1
1988.96 square-feet        1
3881.29 square-feet        1
976 square-feet            1
975 square-feet            1
868.5 square-feet          1
4600 square-feet           1
2538 square-feet           1
2358 square-feet           1
1780 square-feet           1
474.22 square-feet         1
675.51 square-feet         1
2927.59 square-feet        1
809.54 square-feet         1
749.66 square-feet         1
1000.812 square-feet       1
633.28 square-feet         1
765 square-feet            1
695 square-feet            1
405 square-feet            1
591.14 square-feet         1
1317.6 square-feet         1
687 square-feet            1
669 square-feet            1
1786.5 square-feet         1
606.18 square-feet         1
487 square-feet            1
811 square-feet            1
947 square-feet            1
1009.64 square-feet        1
925.6 square-feet          1
1989.624 square-feet       1
860 square-feet            1
1847.61 square-feet        1
2517 square-feet           1
960 square-feet            1
984.34 square-feet         1
948.72 square-feet         1
107.4 square-meter         1
2665 square-feet           1
607.32 square-feet         1
2325 square-feet           1
2190 square-feet           1
622 square-feet            1
795 square-feet            1
2627.07 square-feet        1
63.97 square-meter         1
2243 square-feet           1
1326.18 square-feet        1
916 square-feet            1
700.2 square-feet          1
3839 square-feet           1
2293.43 square-feet        1
950.25 square-feet         1
967.08 square-feet         1
1625.87 square-feet        1
90 square-meter            1
2979.87 square-feet        1
2362.83 square-feet        1
3902 square-feet           1
725 square-feet            1
2770.07 square-feet        1
2104 aana                  1
718 square-feet            1
Name: count, dtype: int64

In [28]:
# ─────────────────────────────────────────
# STEP 5 — PARSE built_up_area → built_up_sqft
# Keeping original built_up_area intact
# Units found:
#   square-feet → keep as is
#   aana → most are genuine aana BUT
#          large values like 1026.75, 855.625 are
#          actually sqft with wrong label — detect by size
#          Real aana built up: 1–20 aana max
#          Fake aana (actually sqft): values > 50
#   square-meter → multiply by 10.764
#   paisa → 1 aana = 4 paisa → paisa/4 × 342.25
#   plain number with no unit → assume sqft
# ─────────────────────────────────────────

def parse_built_up_area(val):
    if pd.isna(val):
        return np.nan

    val = str(val).strip().lower()

    # Extract numeric value
    num_match = re.search(r'(\d+\.?\d*)', val)
    if not num_match:
        return np.nan
    num = float(num_match.group(1))

    if 'square-feet' in val or 'square feet' in val:
        # Standard sqft — return directly
        return num

    elif 'sq' in val and 'meter' in val:
        # Square meter → convert to sqft
        # 1 sqm = 10.764 sqft
        # Example: "139.09 square-meter" → 1497.23 sqft
        return round(num * 10.764, 2)

    elif 'aana' in val or 'anna' in val:
        # Two cases:
        # Real aana: small values like "3 aana", "4.5 aana" → convert to sqft
        # Fake aana (actually sqft): large values like "1026.75 aana" → keep as sqft
        # Threshold: if value > 50 it's almost certainly sqft mislabeled as aana
        if num > 50:
            # Mislabeled — treat as sqft directly
            # Example: "1026.75 aana" → 1026.75 sqft
            return num
        else:
            # Genuine aana — convert to sqft
            # Example: "3 aana" → 3 × 342.25 = 1026.75 sqft
            return round(num * 342.25, 2)

    elif 'paisa' in val:
        # 4 paisa = 1 aana = 342.25 sqft
        # Example: "3 paisa" → (3/4) × 342.25 = 256.69 sqft
        return round((num / 4) * 342.25, 2)

    elif 'ropani' in val:
        # 1 ropani = 16 aana = 16 × 342.25 sqft
        # Example: "1 ropani" → 5476 sqft
        return round(num * 16 * 342.25, 2)

    else:
        # No unit found — plain number like "1369"
        # Assume sqft as that's the most common unit
        return num

# Create new column — keep original intact
df_lph['built_up_sqft'] = df_lph['built_up_area'].apply(parse_built_up_area)

# Verify
print("=== built_up_sqft stats ===")
print(df_lph['built_up_sqft'].describe())
print(f"\nNulls: {df_lph['built_up_sqft'].isnull().sum()}")
print(f"Below 100 sqft:   {(df_lph['built_up_sqft'] < 100).sum()}")
print(f"Above 15000 sqft: {(df_lph['built_up_sqft'] > 15000).sum()}")

# Check suspicious values
print("\n=== Below 100 sqft ===")
print(df_lph[df_lph['built_up_sqft'] < 100][['built_up_area', 'built_up_sqft']].head(10))

print("\n=== Above 15000 sqft ===")
print(df_lph[df_lph['built_up_sqft'] > 15000][['built_up_area', 'built_up_sqft']].head(10))

=== built_up_sqft stats ===
count     1723.000000
mean      1480.219162
std        883.758127
min          2.500000
25%       1000.000000
50%       1197.880000
75%       1711.250000
max      10000.000000
Name: built_up_sqft, dtype: float64

Nulls: 467
Below 100 sqft:   8
Above 15000 sqft: 0

=== Below 100 sqft ===
          built_up_area  built_up_sqft
318   85.56 square-feet          85.56
369    57.6 square-feet          57.60
812     2.5 square-feet           2.50
894       4 square-feet           4.00
926     3.5 square-feet           3.50
1176    2.5 square-feet           2.50
1304    3.5 square-feet           3.50
1522   2.75 square-feet           2.75

=== Above 15000 sqft ===
Empty DataFrame
Columns: [built_up_area, built_up_sqft]
Index: []

In [29]:
# ─────────────────────────────────────────
# STEP 6 — FIX year_built
# Two calendar systems mixed in data:
#   BS (Bikram Sambat) — Nepal calendar
#     Example: 2081, 2080, 2079 → clearly BS (>2025 impossible in AD)
#   AD (Anno Domini) — Western calendar
#     Example: 2024, 2023, 2022 → could be AD or BS
# Rule:
#   If year > 2025 → definitely BS → convert to AD by subtracting 56
#   If year <= 2025 → could be AD already → keep as is
#   If year < 1950 → too old, suspicious → NaN
# Example:
#   2081 BS → 2081 - 56 = 2025 AD ✅
#   2060 BS → 2060 - 56 = 2004 AD ✅
#   2024 AD → keep as 2024 AD ✅
# ─────────────────────────────────────────

print("=== Raw year_built distribution ===")
print(df_lph['year_built'].value_counts().sort_index().to_string())

=== Raw year_built distribution ===
year_built
1975 AD        1
1990           1
1994           1
1997           1
1998           4
20             1
2000           4
2001           1
2002           2
2003           3
2004           1
2005           4
2006           2
2007           5
2007 AD        1
2008           3
2009           1
2010           5
2010 A.D       1
2011           2
2011 AD        1
2012           4
2013           1
2014          10
2015           5
2016          11
2016 A.D       1
2016 AD        1
2017          13
2018          22
2019          20
2020          17
2021          27
2021 AD        1
2021 AS        1
2022          46
2022 A D       1
2022 A.D       1
2022 AD        1
20222          1
2023          43
2023 A D       1
2024         251
2024 A.D.      1
2024 AD        2
2025          85
2030           2
2035           2
2036           1
2037           1
2038           2
2040           7
2041           1
2045           4
2046           1
2047           3
2048           6
2049           1
2050          22
2050 BS        1
2052           5
2053           6
2054           7
2055           8
2055 BS        1
2056           4
2057           5
2058           7
2059           5
2060          40
2060 BS        1
2061           6
2062          13
2062 B S       1
2062+2079      1
2063          13
2064          18
2064BS         1
2065          42
2065 B S       1
2065 B.S       1
2066          11
2066 B S       1
2066 BS        1
2067          15
2068          33
2068 BS        1
2069           8
2069 B S       1
2069 B.S       1
2070          43
2070 B S       1
2070 BS        2
2070BS         1
2071          27
2071 BS        1
2072          41
2073          51
2073 B.S       2
2073 BS        2
2074          63
2074 B S       2
2074 BS        1
2075          61
2075 B.S       1
2075BS         1
2076          60
2076 BS        5
2077          44
2077 B.S       1
2077 BS        1
2078          78
2078 BS        4
2078BS         1
2079          72
2079 BS        4
2080          94
2080 B S       1
2081         151
2081 B S       1
2082          78
2082 B S       3
2082 BS        1
2083           1
2089           1
79             1
B.S 2076       1

In [30]:
# ─────────────────────────────────────────
# STEP 6 — FIX year_built
# ─────────────────────────────────────────

def parse_year_built(val):
    if pd.isna(val):
        return np.nan

    val = str(val).strip()

    # Remove all spaces for easier matching
    val_clean = val.replace(' ', '').upper()

    # Garbage cases — return NaN
    # "2062+2079" has + sign, "20" too short, "79" too short
    if '+' in val_clean:
        return np.nan
    if len(re.sub(r'[^0-9]', '', val_clean)) < 4:
        return np.nan
    if val_clean in ['20222']:
        return np.nan

    # Extract the 4-digit year number
    num_match = re.search(r'(\d{4})', val_clean)
    if not num_match:
        return np.nan
    year = int(num_match.group(1))

    # Explicitly marked as AD — keep as is
    # Example: "1975 AD", "2007 AD", "2022 A.D", "2010 A.D"
    if 'AD' in val_clean or 'A.D' in val_clean:
        return year

    # Explicitly marked as BS — subtract 56
    # Example: "2050 BS", "2076 BS", "B.S 2076", "2021 AS" (typo for BS)
    if 'BS' in val_clean or 'B.S' in val_clean or 'AS' in val_clean:
        return year - 56

    # Now handle plain numbers by range
    if year > 2025:
        # Impossible to be AD (future) — must be BS
        # Example: 2081 BS → 2081 - 56 = 2025 AD
        return year - 56
    elif 1950 <= year <= 2025:
        # Could be AD — treat as AD directly
        # Example: 2024 → 2024 AD
        return year
    else:
        # Too old or weird — NaN
        return np.nan

df_lph['year_built_ad'] = df_lph['year_built'].apply(parse_year_built)

In [31]:
# Verify
print("=== year_built_ad stats ===")
print(df_lph['year_built_ad'].describe())
print(f"\nNulls: {df_lph['year_built_ad'].isnull().sum()}")
print(f"Before 1990: {(df_lph['year_built_ad'] < 1990).sum()}")
print(f"After 2025:  {(df_lph['year_built_ad'] > 2025).sum()}")
print(f"\n=== Distribution ===")
print(df_lph['year_built_ad'].value_counts().sort_index().to_string())

=== year_built_ad stats ===
count    1823.000000
mean     2018.206253
std         8.602021
min      1965.000000
25%      2016.000000
50%      2022.000000
75%      2024.000000
max      2033.000000
Name: year_built_ad, dtype: float64

Nulls: 367
Before 1990: 22
After 2025:  84

=== Distribution ===
year_built_ad
1965.0      1
1974.0      2
1975.0      1
1979.0      2
1980.0      1
1981.0      1
1982.0      2
1984.0      7
1985.0      1
1989.0      4
1990.0      2
1991.0      3
1992.0      6
1993.0      1
1994.0     24
1996.0      5
1997.0      7
1998.0     11
1999.0      9
2000.0      8
2001.0      6
2002.0      9
2003.0      8
2004.0     42
2005.0     10
2006.0     16
2007.0     19
2008.0     22
2009.0     45
2010.0     19
2011.0     18
2012.0     38
2013.0     11
2014.0     57
2015.0     33
2016.0     54
2017.0     68
2018.0     88
2019.0     83
2020.0     83
2021.0     74
2022.0    132
2023.0    120
2024.0    349
2025.0    237
2026.0     82
2027.0      1
2033.0      1

In [32]:
from datetime import datetime

# ─────────────────────────────────────────
# FIX YEAR_BUILT EDGE CASES
# Why: 2026-2033 are future years — these are
# under construction properties listed in advance
# Cap at current year since we can't verify completion
# Why keep pre-1990: Old houses are valid listings
# just rare in Kathmandu valley market
# ─────────────────────────────────────────

# Get current year dynamically
current_year = datetime.now().year
print(f"Current year: {current_year}")

# Cap future years at current year
# Why: Under construction listings show future completion year
# We cap at current year since house doesn't exist yet
df_lph['year_built_ad'] = df_lph['year_built_ad'].clip(upper=current_year)

# Calculate house age from current year
# Why age over raw year: Model learns "5 year old house costs X"
# which generalizes better than "house built in 2020 costs X"
# Example: year_built=2020, current_year=2026 → age=6
df_lph['house_age'] = current_year - df_lph['year_built_ad']

print("\n=== house_age stats ===")
print(df_lph['house_age'].describe())
print(f"\nNulls: {df_lph['house_age'].isnull().sum()}")
print(f"Age 0 (brand new):  {(df_lph['house_age'] == 0).sum()}")
print(f"Age above 40:       {(df_lph['house_age'] > 40).sum()}")
print(f"\nMost common ages:")
print(df_lph['house_age'].value_counts().sort_index().head(15))

Current year: 2026

=== house_age stats ===
count    1823.000000
mean        7.798135
std         8.596444
min         0.000000
25%         2.000000
50%         4.000000
75%        10.000000
max        61.000000
Name: house_age, dtype: float64

Nulls: 367
Age 0 (brand new):  84
Age above 40:       18

Most common ages:
house_age
0.0      84
1.0     237
2.0     349
3.0     120
4.0     132
5.0      74
6.0      83
7.0      83
8.0      88
9.0      68
10.0     54
11.0     33
12.0     57
13.0     11
14.0     38
Name: count, dtype: int64

In [33]:
df_lph['road_access'].value_counts()

road_access
13 Feet      933
20 Feet      380
16 Feet      174
10 Feet      159
12 Feet       80
14 Feet       65
26 Feet       57
18 Feet       49
8 Feet        33
15 Feet       33
11 Feet       28
22 Feet       25
4 Feet        18
30 Feet       12
50 Feet       11
6 Feet        11
5 Feet        11
28 Feet       10
24 Feet       10
36 Feet        9
9 Feet         8
3 Feet         8
21 Feet        7
23 Feet        6
40 Feet        5
32 Feet        5
25 Feet        4
20 Meter       3
27 Feet        3
19 Feet        2
7 Feet         2
33 Feet        2
35 Feet        2
7.5 Meter      2
48 Feet        2
42 Feet        2
14.5 Feet      1
15.4 Feet      1
75 Feet        1
100 Feet       1
30 Meter       1
13.5 Feet      1
44 Feet        1
29 Feet        1
52 Feet        1
12.5 Feet      1
17 Feet        1
31 Feet        1
Name: count, dtype: int64

In [34]:
# ─────────────────────────────────────────
# STEP 7 — PARSE road_access → road_width_feet
# Units found:
#   Feet → keep as is (main unit)
#   Meter → convert to feet (1 meter = 3.281 feet)
#   Decimal feet → keep as is e.g. "14.5 Feet" → 14.5
# Keeping original road_access column intact
# ─────────────────────────────────────────

def parse_road_access(val):
    if pd.isna(val):
        return np.nan

    val = str(val).strip().lower()

    # Extract numeric value
    num_match = re.search(r'(\d+\.?\d*)', val)
    if not num_match:
        return np.nan
    num = float(num_match.group(1))

    if 'meter' in val:
        # Convert meters to feet
        # 1 meter = 3.281 feet
        # Example: "20 Meter" → 20 × 3.281 = 65.62 feet
        # Example: "7.5 Meter" → 7.5 × 3.281 = 24.61 feet
        return round(num * 3.281, 1)
    else:
        # Already in feet — return directly
        # Example: "13 Feet" → 13, "14.5 Feet" → 14.5
        return num

# Create new column — keep original intact
df_lph['road_width_feet'] = df_lph['road_access'].apply(parse_road_access)

print("=== road_width_feet stats ===")
print(df_lph['road_width_feet'].describe())
print(f"\nNulls: {df_lph['road_width_feet'].isnull().sum()}")
print(f"Below 3 feet:   {(df_lph['road_width_feet'] < 3).sum()}")
print(f"Above 80 feet:  {(df_lph['road_width_feet'] > 80).sum()}")
print(f"\nValue distribution:")
print(df_lph['road_width_feet'].value_counts().head(10))

=== road_width_feet stats ===
count    2183.000000
mean       15.547091
std         6.632852
min         3.000000
25%        13.000000
50%        13.000000
75%        20.000000
max       100.000000
Name: road_width_feet, dtype: float64

Nulls: 7
Below 3 feet:   0
Above 80 feet:  2

Value distribution:
road_width_feet
13.0    933
20.0    380
16.0    174
10.0    159
12.0     80
14.0     65
26.0     57
18.0     49
8.0      33
15.0     33
Name: count, dtype: int64

In [35]:
# ─────────────────────────────────────────
# STEP 8 — CONVERT DISTANCE COLUMNS TO METERS
# Same function as lalpurja land dataset
# Handles: "1km" → 1000, "500m" → 500, "1.5km" → 1500
# Using re.search to safely extract numbers
# Keeping original columns intact
# ─────────────────────────────────────────

def convert_to_meters(val):
    if pd.isna(val):
        return np.nan

    val = str(val).strip().lower()

    # Use regex to extract first valid number
    # Safely handles formats like "1km", "500m", "1.5km", "2.5km"
    num_match = re.search(r'(\d+\.?\d*)', val)
    if not num_match:
        return np.nan
    num = float(num_match.group(1))

    if 'km' in val:
        # Multiply by 1000 to convert km → meters
        # Example: "1km" → 1000, "1.5km" → 1500
        return num * 1000
    elif 'm' in val:
        # Already in meters — return as is
        # Example: "500m" → 500, "200m" → 200
        return num

    return np.nan

# Distance columns in this dataset
# Note: ring_road is also a distance column
distance_cols = ['hospital', 'airport', 'pharmacy', 'bhatbhateni',
                 'school', 'college', 'gym', 'public_transport',
                 'police_station', 'pashupatinath', 'boudhanath',
                 'atm', 'hotel', 'restaurant', 'banquet', 'ring_road']

for col in distance_cols:
    df_lph[col + '_m'] = df_lph[col].apply(convert_to_meters)
    print(f"✅ {col} → {col}_m converted")

print("\n=== Sample converted distances ===")
print(df_lph[['hospital_m', 'airport_m', 'school_m', 'ring_road_m']].describe().round(0))

print(f"\n=== Nulls after conversion ===")
new_dist_cols = [col + '_m' for col in distance_cols]
nulls = df_lph[new_dist_cols].isnull().sum()
print(nulls)

✅ hospital → hospital_m converted
✅ airport → airport_m converted
✅ pharmacy → pharmacy_m converted
✅ bhatbhateni → bhatbhateni_m converted
✅ school → school_m converted
✅ college → college_m converted
✅ gym → gym_m converted
✅ public_transport → public_transport_m converted
✅ police_station → police_station_m converted
✅ pashupatinath → pashupatinath_m converted
✅ boudhanath → boudhanath_m converted
✅ atm → atm_m converted
✅ hotel → hotel_m converted
✅ restaurant → restaurant_m converted
✅ banquet → banquet_m converted
✅ ring_road → ring_road_m converted

=== Sample converted distances ===
       hospital_m  airport_m  school_m  ring_road_m
count      1914.0     1942.0    1814.0       1517.0
mean       2064.0     6411.0    1231.0       2717.0
std       22266.0     3038.0   19898.0       2718.0
min           0.0        8.0       0.0          0.0
25%         400.0     4000.0     100.0        800.0
50%         800.0     6000.0     200.0       2000.0
75%        1200.0     8000.0     500.0       4000.0
max      600000.0    19000.0  600000.0      25000.0

=== Nulls after conversion ===
hospital_m            276
airport_m             248
pharmacy_m            526
bhatbhateni_m         534
school_m              376
college_m             635
gym_m                 832
public_transport_m    265
police_station_m      694
pashupatinath_m       283
boudhanath_m          346
atm_m                 860
hotel_m               869
restaurant_m          864
banquet_m             901
ring_road_m           673
dtype: int64

In [36]:
# ─────────────────────────────────────────
# CAP UNREALISTIC DISTANCE VALUES
# Same approach as lalpurja land dataset
# Realistic maximum distances for Kathmandu valley
# ─────────────────────────────────────────
distance_caps = {
    'hospital_m':          15000,   # 15km max
    'airport_m':           30000,   # 30km max
    'pharmacy_m':          10000,   # 10km max
    'bhatbhateni_m':       15000,   # 15km max
    'school_m':            10000,   # 10km max
    'college_m':           15000,   # 15km max
    'gym_m':               10000,   # 10km max
    'public_transport_m':   5000,   # 5km max
    'police_station_m':    15000,   # 15km max
    'pashupatinath_m':     30000,   # 30km max
    'boudhanath_m':        30000,   # 30km max
    'atm_m':                5000,   # 5km max
    'hotel_m':             15000,   # 15km max
    'restaurant_m':        10000,   # 10km max
    'banquet_m':           15000,   # 15km max
    'ring_road_m':         30000,   # 30km max
}

for col, cap in distance_caps.items():
    over_cap = (df_lph[col] > cap).sum()
    if over_cap > 0:
        print(f"⚠️  {col}: {over_cap} rows exceed {cap}m — capping")
    df_lph.loc[df_lph[col] > cap, col] = np.nan

print("\n=== Distance stats after capping ===")
key_cols = ['hospital_m', 'airport_m', 'school_m',
            'ring_road_m', 'public_transport_m']
print(df_lph[key_cols].describe().round(0))

# ─────────────────────────────────────────
# DECISION ON HIGH-NULL DISTANCE COLUMNS
# gym, atm, hotel, restaurant, banquet
# have 800-900 nulls out of 2190 rows (40%+)
# These are less critical amenities for house pricing
# Check if they add value before deciding to keep or drop
# ─────────────────────────────────────────
new_dist_cols = [col + '_m' for col in distance_cols]
print("\n=== Null % per distance column ===")
for col in new_dist_cols:
    null_pct = df_lph[col].isnull().sum() / len(df_lph) * 100
    print(f"{col}: {null_pct:.1f}%")

⚠️  hospital_m: 5 rows exceed 15000m — capping
⚠️  pharmacy_m: 8 rows exceed 10000m — capping
⚠️  bhatbhateni_m: 1 rows exceed 15000m — capping
⚠️  school_m: 5 rows exceed 10000m — capping
⚠️  college_m: 2 rows exceed 15000m — capping
⚠️  gym_m: 1 rows exceed 10000m — capping
⚠️  public_transport_m: 1 rows exceed 5000m — capping
⚠️  police_station_m: 1 rows exceed 15000m — capping
⚠️  pashupatinath_m: 1 rows exceed 30000m — capping
⚠️  boudhanath_m: 1 rows exceed 30000m — capping
⚠️  atm_m: 9 rows exceed 5000m — capping
⚠️  hotel_m: 5 rows exceed 15000m — capping
⚠️  restaurant_m: 4 rows exceed 10000m — capping
⚠️  banquet_m: 5 rows exceed 15000m — capping

=== Distance stats after capping ===
       hospital_m  airport_m  school_m  ring_road_m  public_transport_m
count      1909.0     1942.0    1809.0       1517.0              1924.0
mean       1048.0     6411.0     350.0       2717.0               243.0
std        1023.0     3038.0     458.0       2718.0               249.0
min           0.0        8.0       0.0          0.0                 0.0
25%         400.0     4000.0     100.0        800.0               100.0
50%         800.0     6000.0     200.0       2000.0               150.0
75%        1100.0     8000.0     500.0       4000.0               350.0
max        8500.0    19000.0    8700.0      25000.0              3700.0

=== Null % per distance column ===
hospital_m: 12.8%
airport_m: 11.3%
pharmacy_m: 24.4%
bhatbhateni_m: 24.4%
school_m: 17.4%
college_m: 29.1%
gym_m: 38.0%
public_transport_m: 12.1%
police_station_m: 31.7%
pashupatinath_m: 13.0%
boudhanath_m: 15.8%
atm_m: 39.7%
hotel_m: 39.9%
restaurant_m: 39.6%
banquet_m: 41.4%
ring_road_m: 30.7%

✅ Keep (null % below 25%, meaningful for house pricing):

hospital_m (12.8%), airport_m (11.3%), school_m (17.4%)
public_transport_m (12.1%), pashupatinath_m (13.0%)
boudhanath_m (15.8%), pharmacy_m (24.4%), bhatbhateni_m (24.4%)

🟡 Keep but impute carefully (25-35% nulls, still useful):

college_m (29.1%), ring_road_m (30.7%), police_station_m (31.7%)

🔴 Drop (40%+ nulls, less important for house pricing):

gym_m (38%), atm_m (39.7%), hotel_m (39.9%), restaurant_m (39.6%), banquet_m (41.4%)

In [37]:
# ─────────────────────────────────────────
# DROP HIGH NULL DISTANCE COLUMNS
# gym, atm, hotel, restaurant, banquet
# all have 38-41% nulls — too many to impute reliably
# Also not strong price predictors for housing
# Keeping original columns intact as always
# ─────────────────────────────────────────
high_null_cols = ['gym_m', 'atm_m', 'hotel_m', 'restaurant_m', 'banquet_m']

print(f"Dropping: {high_null_cols}")
df_lph.drop(columns=high_null_cols, inplace=True)

print(f"\nShape after dropping: {df_lph.shape}")

Dropping: ['gym_m', 'atm_m', 'hotel_m', 'restaurant_m', 'banquet_m']

Shape after dropping: (2190, 49)

In [38]:
# ─────────────────────────────────────────
# STEP 9 — STANDARDIZE road_type
# Same mapping as lalpurja land dataset
# ─────────────────────────────────────────
road_map = {
    'Blacktopped':      'High Access',
    'Paved':            'High Access',
    'Gravelled':        'Low Access',
    'Soil Stabilized':  'Low Access',
    'alley':            'Low Access'
}
df_lph['road_type'] = df_lph['road_type'].replace(road_map)

print("\n=== road_type after standardization ===")
print(df_lph['road_type'].value_counts())

=== road_type after standardization ===
road_type
High Access    1643
Low Access      535
Name: count, dtype: int64

In [39]:
# ─────────────────────────────────────────
# STEP 10 — CHECK ALL NULLS BEFORE FILLING
# Get a complete picture of what needs filling
# ─────────────────────────────────────────
print("=== Current null situation ===")
nulls = df_lph.isnull().sum()
null_pct = (nulls / len(df_lph) * 100).round(1)
null_df = pd.DataFrame({'count': nulls, 'pct': null_pct})
print(null_df[null_df['count'] > 0].sort_values('count', ascending=False).to_string())

=== Current null situation ===
                    count   pct
dimension            1395  63.7
banquet               876  40.0
hotel                 863  39.4
atm                   850  38.8
restaurant            846  38.6
gym                   800  36.5
police_station_m      695  31.7
ring_road_m           673  30.7
police_station        668  30.5
ring_road             662  30.2
college_m             637  29.1
college               627  28.6
bhatbhateni_m         535  24.4
pharmacy_m            534  24.4
bhatbhateni           526  24.0
pharmacy              519  23.7
built_up_sqft         467  21.3
built_up_area         467  21.3
ward_no               442  20.2
municipality          395  18.0
school_m              381  17.4
year_built_ad         367  16.8
house_age             367  16.8
year_built            363  16.6
school                362  16.5
boudhanath_m          347  15.8
boudhanath            341  15.6
pashupatinath_m       284  13.0
furnishing            282  12.9
hospital_m            281  12.8
pashupatinath         279  12.7
public_transport_m    266  12.1
public_transport      253  11.6
hospital              249  11.4
airport_m             248  11.3
airport               247  11.3
property_face          99   4.5
road_type              12   0.5
road_access             7   0.3
road_width_feet         7   0.3
neighborhood            2   0.1
land_size_aana          1   0.0

In [40]:
df=df_lph.copy()

In [41]:
df.columns

Index(['district', 'property_type', 'property_face', 'year_built', 'road_type',
       'negotiable', 'furnishing', 'property_area', 'built_up_area',
       'road_access', 'dimension', 'date_posted', 'views', 'municipality',
       'ward_no', 'ring_road', 'hospital', 'airport', 'pharmacy',
       'bhatbhateni', 'school', 'college', 'gym', 'public_transport',
       'police_station', 'pashupatinath', 'boudhanath', 'atm', 'hotel',
       'restaurant', 'banquet', 'neighborhood', 'total_price',
       'land_size_aana', 'built_up_sqft', 'year_built_ad', 'house_age',
       'road_width_feet', 'hospital_m', 'airport_m', 'pharmacy_m',
       'bhatbhateni_m', 'school_m', 'college_m', 'public_transport_m',
       'police_station_m', 'pashupatinath_m', 'boudhanath_m', 'ring_road_m'],
      dtype='object')

In [42]:
# 1. Structural Overview (Columns, Dtypes, Memory)
print("--- 🏗️ DATASET STRUCTURE ---")
print(ktm.info())

# 2. Numerical Summary (Prices, Areas, Ages, Distances)
print("\n--- 🔢 NUMERICAL STATISTICS ---")
# include=[np.number] focuses on math columns
print(ktm.describe())

# 3. Categorical Summary (Neighborhoods, Municipalities, Face)
print("\n--- 🏷️ CATEGORICAL SUMMARY ---")
# include=['object'] focuses on text labels
print(ktm.describe(include=['object']))

# 4. The "Null Map" (Crucial for your Imputation step)
print("\n--- 🕳️ MISSING VALUE AUDIT ---")
null_counts = ktm.isnull().sum()
null_pct = (null_counts / len(ktm)) * 100
null_report = pd.DataFrame({'Missing Count': null_counts, 'Percentage (%)': null_pct})
print(null_report[null_report['Missing Count'] > 0].sort_values(by='Percentage (%)', ascending=False))

--- 🏗️ DATASET STRUCTURE ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1605 entries, 0 to 1604
Data columns (total 43 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   url               1605 non-null   object
 1   source            1605 non-null   object
 2   category          1605 non-null   object
 3   district          1605 non-null   object
 4   property_id       1605 non-null   int64
 5   title             1599 non-null   object
 6   total_price_raw   1604 non-null   object
 7   property_type     1604 non-null   object
 8   property_face     1513 non-null   object
 9   year_built        1214 non-null   object
 10  road_type         1592 non-null   object
 11  negotiable        1604 non-null   object
 12  furnishing        1305 non-null   object
 13  city_area         1604 non-null   object
 14  pricing_raw       1604 non-null   object
 15  purpose           1604 non-null   object
 16  property_area     1604 non-null   object
 17  built_up_area     1163 non-null   object
 18  road_access       1595 non-null   object
 19  dimension         604 non-null    object
 20  date_posted       1604 non-null   object
 21  views             1604 non-null   float64
 22  municipality      1295 non-null   object
 23  ward_no           1267 non-null   object
 24  ring_road         1051 non-null   object
 25  landmark          1569 non-null   object
 26  hospital          1353 non-null   object
 27  airport           1365 non-null   object
 28  pharmacy          1137 non-null   object
 29  bhatbhateni       1083 non-null   object
 30  school            1249 non-null   object
 31  college           1041 non-null   object
 32  gym               896 non-null    object
 33  public_transport  1350 non-null   object
 34  police_station    987 non-null    object
 35  pashupatinath     1335 non-null   object
 36  boudhanath        1299 non-null   object
 37  atm               852 non-null    object
 38  hotel             838 non-null    object
 39  restaurant        841 non-null    object
 40  banquet           809 non-null    object
 41  ward_office       1239 non-null   object
 42  neighborhood      1602 non-null   object
dtypes: float64(1), int64(1), object(41)
memory usage: 539.3+ KB
None

--- 🔢 NUMERICAL STATISTICS ---
       property_id        views
count  1605.000000  1604.000000
mean   5364.967601   382.526808
std    1914.441487   261.515765
min    2315.000000    85.000000
25%    3692.000000   230.000000
50%    5317.000000   318.000000
75%    7104.000000   455.000000
max    8573.000000  3600.000000

--- 🏷️ CATEGORICAL SUMMARY ---
                                                      url    source category  \
count                                                1605      1605     1605
unique                                               1605         1        1
top     https://lalpurjanepal.com.np/properties/house-...  lalpurja    house
freq                                                    1      1605     1605

         district             title  total_price_raw property_type  \
count        1605              1599             1604          1604
unique          1                 1              345             3
top     Kathmandu  Property Details  3 Crore 50 Lakh   Residential
freq         1605              1599               64          1312

       property_face year_built    road_type negotiable      furnishing  \
count           1513       1214         1592       1604            1305
unique            12        119            5          2               3
top             East       2081  Blacktopped        Yes  Semi Furnished
freq             364        117          960       1578             654

                        city_area      pricing_raw purpose property_area  \
count                        1604             1604    1604          1604
unique                        127              345       1           246
top     Kathmandu, Budhanilkantha  3 Crore 50 Lakh    Sale        4 Aana
freq                          290               64    1604           180

           built_up_area road_access  dimension       date_posted  \
count               1163        1595        604              1604
unique               328          41        212               362
top     1369 square-feet     13 Feet  F 30 Feet  2024 December 20
freq                 116         634         61                24

       municipality ward_no ring_road         landmark hospital airport  \
count          1295    1267      1051             1569     1353    1365
unique           81      47       100             1162      129     129
top       Kathmandu      08       2km  Grande Hospital      1km     7km
freq            440     137       167               16      319     190

       pharmacy bhatbhateni school college   gym public_transport  \
count      1137        1083   1249    1041   896             1350
unique       70         111    112     107    58               77
top        200m         1km   100m    500m  500m             100m
freq        318         228    263     224   243              290

       police_station pashupatinath boudhanath   atm hotel restaurant banquet  \
count             987          1335       1299   852   838        841     809
unique             83           144        120    65    60         60      65
top              500m           5km        4km  200m  200m       200m    500m
freq              271           151        150   183   156        206     166

       ward_office    neighborhood
count         1239            1602
unique         125             126
top            1km  Budhanilkantha
freq           289             290

--- 🕳️ MISSING VALUE AUDIT ---
                  Missing Count  Percentage (%)
dimension                  1001       62.367601
banquet                     796       49.595016
hotel                       767       47.788162
restaurant                  764       47.601246
atm                         753       46.915888
gym                         709       44.174455
police_station              618       38.504673
college                     564       35.140187
ring_road                   554       34.517134
bhatbhateni                 522       32.523364
pharmacy                    468       29.158879
built_up_area               442       27.538941
year_built                  391       24.361371
ward_office                 366       22.803738
school                      356       22.180685
ward_no                     338       21.059190
municipality                310       19.314642
boudhanath                  306       19.065421
furnishing                  300       18.691589
pashupatinath               270       16.822430
public_transport            255       15.887850
hospital                    252       15.700935
airport                     240       14.953271
property_face                92        5.732087
landmark                     36        2.242991
road_type                    13        0.809969
road_access                  10        0.623053
title                         6        0.373832
neighborhood                  3        0.186916
total_price_raw               1        0.062305
property_type                 1        0.062305
date_posted                   1        0.062305
property_area                 1        0.062305
views                         1        0.062305
pricing_raw                   1        0.062305
city_area                     1        0.062305
purpose                       1        0.062305
negotiable                    1        0.062305

In [43]:
df_lph.sample(2)

,district,property_type,property_face,year_built,road_type,negotiable,furnishing,property_area,built_up_area,road_access,dimension,date_posted,views,municipality,ward_no,ring_road,hospital,airport,pharmacy,bhatbhateni,school,college,gym,public_transport,police_station,pashupatinath,boudhanath,atm,hotel,restaurant,banquet,neighborhood,total_price,land_size_aana,built_up_sqft,year_built_ad,house_age,road_width_feet,hospital_m,airport_m,pharmacy_m,bhatbhateni_m,school_m,college_m,public_transport_m,police_station_m,pashupatinath_m,boudhanath_m,ring_road_m
1176,Kathmandu,Residential,West,2081,Low Access,Yes,Semi Furnished,3.12 Aana,2.5 square-feet,13 Feet,NaN,2024 October 29,293.0,Kageshwori Manohara,08,3.5 km,3 km,3.5 km,300 m,4 km,300 m,3 km,300 m,300 m,1 km,3.5 km,5 km,300 m,500 m,400 m,500 m,Gothatar,24000000.0,3.12,2.5,2025.0,1.0,13.0,3000.0,3500.0,300.0,4000.0,300.0,3000.0,300.0,1000.0,3500.0,5000.0,3500.0
1595,Lalitpur,Residential,North-West,2075,High Access,Yes,Semi Furnished,4.5 Aana,1095.2 square-feet,20 Feet,F 32 Feet,2025 July 1,109.0,godawari,14,6km,200m,14km,100m,600m,100m,200m,300m,10m,400m,18km,22km,200m,100m,230m,460m,Godawari,27000000.0,4.50,1095.2,2019.0,7.0,20.0,200.0,14000.0,100.0,600.0,100.0,200.0,10.0,400.0,18000.0,22000.0,6000.0

In [44]:
# ─────────────────────────────────────────
# CATEGORY 7 — ROW DELETION
# Why: total_price and property_type are critical
# We cannot guess the target variable (total_price)
# and property_type affects everything else
# Dropping these rows is safer than imputing them
# ─────────────────────────────────────────
before = len(df_lph)

df_lph.dropna(subset=['total_price', 'property_type'], inplace=True)
df_lph.reset_index(drop=True, inplace=True)

print(f"Rows before: {before}")
print(f"Rows after:  {len(df_lph)}")
print(f"Rows dropped: {before - len(df_lph)}")
print(f"\n=== Remaining nulls ===")
nulls = df_lph.isnull().sum()
print(nulls[nulls > 0].sort_values(ascending=False))

Rows before: 2190
Rows after:  2190
Rows dropped: 0

=== Remaining nulls ===
dimension             1395
banquet                876
hotel                  863
atm                    850
restaurant             846
gym                    800
police_station_m       695
ring_road_m            673
police_station         668
ring_road              662
college_m              637
college                627
bhatbhateni_m          535
pharmacy_m             534
bhatbhateni            526
pharmacy               519
built_up_sqft          467
built_up_area          467
ward_no                442
municipality           395
school_m               381
year_built_ad          367
house_age              367
year_built             363
school                 362
boudhanath_m           347
boudhanath             341
pashupatinath_m        284
furnishing             282
hospital_m             281
pashupatinath          279
public_transport_m     266
public_transport       253
hospital               249
airport_m              248
airport                247
property_face           99
road_type               12
road_access              7
road_width_feet          7
neighborhood             2
land_size_aana           1
dtype: int64

In [45]:
# ─────────────────────────────────────────
# CATEGORY 1 — DROP HIGH NULL COLUMNS
# Why: Columns with 40%+ nulls contain more
# fabricated data than real data after imputation
# This makes the model learn false patterns
# Example: gym_m is 38% null — if we fill with median
# we're essentially making up values for 800 rows
# The model might think gym distance matters when
# it's actually just our made-up median repeated
# ─────────────────────────────────────────

drop_cols = [
    # High null amenities — too many missing to impute reliably
    'dimension',     # 63.7% null — already parsed into facing_road_width in land
                     # but housing dimension means something different — drop
    'banquet',       # 40.0% null — not a strong house price predictor
    'hotel',         # 39.4% null — not a strong house price predictor
    'atm',           # 38.8% null — not a strong house price predictor
    'restaurant',    # 38.6% null — not a strong house price predictor
    'gym',           # 36.5% null — not a strong house price predictor

    # Original string distance columns
    # Already converted to _m versions — raw strings no longer needed
    'police_station', 'ring_road', 'college', 'bhatbhateni',
    'pharmacy', 'boudhanath', 'pashupatinath', 'public_transport',
    'hospital', 'airport', 'school',

    # Other raw columns already parsed into cleaner versions
    'road_access',    # → road_width_feet
    'built_up_area',  # → built_up_sqft
    'year_built',     # → house_age
    'year_built_ad',  # → house_age
]

df_lph.drop(columns=drop_cols, inplace=True)

print(f"Shape after dropping: {df_lph.shape}")
print(f"\n=== Remaining columns ===")
print(list(df_lph.columns))

print(f"\n=== Remaining nulls ===")
nulls = df_lph.isnull().sum()
print(nulls[nulls > 0].sort_values(ascending=False))

Shape after dropping: (2190, 28)

=== Remaining columns ===
['district', 'property_type', 'property_face', 'road_type', 'negotiable', 'furnishing', 'property_area', 'date_posted', 'views', 'municipality', 'ward_no', 'neighborhood', 'total_price', 'land_size_aana', 'built_up_sqft', 'house_age', 'road_width_feet', 'hospital_m', 'airport_m', 'pharmacy_m', 'bhatbhateni_m', 'school_m', 'college_m', 'public_transport_m', 'police_station_m', 'pashupatinath_m', 'boudhanath_m', 'ring_road_m']

=== Remaining nulls ===
police_station_m      695
ring_road_m           673
college_m             637
bhatbhateni_m         535
pharmacy_m            534
built_up_sqft         467
ward_no               442
municipality          395
school_m              381
house_age             367
boudhanath_m          347
pashupatinath_m       284
furnishing            282
hospital_m            281
public_transport_m    266
airport_m             248
property_face          99
road_type              12
road_width_feet         7
neighborhood            2
land_size_aana          1
dtype: int64

In [46]:
# ─────────────────────────────────────────
# CATEGORY 3 — CONDITIONAL FILLING
# Why conditional: Some nulls have a logical
# real-world default rather than a statistical one
# ─────────────────────────────────────────

# furnishing → fill with 'Unfurnished'
# Why: In Nepal real estate, if furnishing is not
# mentioned it typically means unfurnished
# It's the conservative safe default
# Example: Listing says nothing about furniture
#          → assume buyer gets empty house → Unfurnished
df_lph['furnishing'] = df_lph['furnishing'].fillna('Unfurnished')
print(f"✅ furnishing filled — distribution:")
print(df_lph['furnishing'].value_counts())

# negotiable → fill with 'Yes'
# Why: We confirmed earlier that 90%+ listings
# are negotiable in Nepal housing market
# NaN likely means seller forgot to mention it
# not that it's non-negotiable
# Example: 1310 out of 1326 lalpurja land were Yes
#          → safe to assume missing = Yes
df_lph['negotiable'] = df_lph['negotiable'].fillna('Yes')
print(f"\n✅ negotiable filled — distribution:")
print(df_lph['negotiable'].value_counts())

# road_type → fill with 'High Access'
# Why: 12 nulls only (0.5%) — very small
# High Access is the most common road type (75%)
# Most Kathmandu urban listings have blacktopped roads
df_lph['road_type'] = df_lph['road_type'].fillna('High Access')
print(f"\n✅ road_type filled — distribution:")
print(df_lph['road_type'].value_counts())

print(f"\n=== Nulls after Category 3 ===")
nulls = df_lph.isnull().sum()
print(nulls[nulls > 0].sort_values(ascending=False))

✅ furnishing filled — distribution:
furnishing
Semi Furnished    1077
Unfurnished        792
Full Furnished     321
Name: count, dtype: int64

✅ negotiable filled — distribution:
negotiable
Yes    2155
No       35
Name: count, dtype: int64

✅ road_type filled — distribution:
road_type
High Access    1655
Low Access      535
Name: count, dtype: int64

=== Nulls after Category 3 ===
police_station_m      695
ring_road_m           673
college_m             637
bhatbhateni_m         535
pharmacy_m            534
built_up_sqft         467
ward_no               442
municipality          395
school_m              381
house_age             367
boudhanath_m          347
pashupatinath_m       284
hospital_m            281
public_transport_m    266
airport_m             248
property_face          99
road_width_feet         7
neighborhood            2
land_size_aana          1
dtype: int64

In [47]:
# ─────────────────────────────────────────
# CATEGORY 2 — LOGIC BASED DEDUCTION
# How it works: Geography is hierarchical in Nepal
#   neighborhood → municipality → district
# If we know a property is in "Budhanilkantha"
# we can reliably infer its municipality is
# "Budhanilkantha" and district is "Kathmandu"
# This is more accurate than statistical imputation
# because it's based on actual geographic facts
#
# Example:
#   Row has neighborhood="Imadol", municipality=NaN
#   Other rows with neighborhood="Imadol" have
#   municipality="Mahalaxmi" (most common)
#   → fill NaN with "Mahalaxmi" ✅ geographically correct
# ─────────────────────────────────────────

# FIX — Convert ward_no to numeric first

df_lph['ward_no'] = pd.to_numeric(df_lph['ward_no'], errors='coerce')
print(f"ward_no dtype: {df_lph['ward_no'].dtype}")
print(f"ward_no nulls after conversion: {df_lph['ward_no'].isnull().sum()}")

# Step 1 — Fill neighborhood first (only 2 nulls)
# Use district mode as fallback — very few nulls
df_lph['neighborhood'] = df_lph.groupby('district')['neighborhood']\
    .transform(lambda x: x.fillna(x.mode()[0] if not x.mode().empty else 'Unknown'))
print(f"✅ neighborhood nulls filled: {df_lph['neighborhood'].isnull().sum()}")

# Step 2 — Fill municipality using neighborhood mode
# Why neighborhood: Properties in same neighborhood
# almost always belong to same municipality
# Example: All "Imadol" properties → "Mahalaxmi"
df_lph['municipality'] = df_lph.groupby('neighborhood')['municipality']\
    .transform(lambda x: x.fillna(x.mode()[0] if not x.mode().empty else np.nan))

# Fill remaining using district mode as fallback
df_lph['municipality'] = df_lph.groupby('district')['municipality']\
    .transform(lambda x: x.fillna(x.mode()[0] if not x.mode().empty else 'Unknown'))
print(f"✅ municipality nulls filled: {df_lph['municipality'].isnull().sum()}")

# Step 3 — Fill ward_no using neighborhood mode
# Why neighborhood: Ward numbers are geographically
# consistent — all properties in "Imadol" are
# typically in the same ward (Ward 3 of Mahalaxmi)
# Example:
#   Row has neighborhood="Imadol", ward_no=NaN
#   Other "Imadol" rows have ward_no=3 (most common)
#   → fill with 3 ✅ geographically accurate
df_lph['ward_no'] = df_lph.groupby('neighborhood')['ward_no']\
    .transform(lambda x: x.fillna(x.mode()[0] if not x.mode().empty else np.nan))

# Fill remaining using municipality median as fallback
df_lph['ward_no'] = df_lph.groupby('municipality')['ward_no']\
    .transform(lambda x: x.fillna(x.median() if not x.empty else np.nan))

# Fill any last remaining with global median
df_lph['ward_no'] = df_lph['ward_no'].fillna(df_lph['ward_no'].median())
print(f"✅ ward_no nulls filled: {df_lph['ward_no'].isnull().sum()}")

print(f"\n=== Nulls after Category 2 ===")
nulls = df_lph.isnull().sum()
print(nulls[nulls > 0].sort_values(ascending=False))

ward_no dtype: float64
ward_no nulls after conversion: 445
✅ neighborhood nulls filled: 0

C:\Users\DELL\AppData\Local\Temp\ipykernel_13424\2712963814.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .transform(lambda x: x.fillna(x.mode()[0] if not x.mode().empty else np.nan))

✅ municipality nulls filled: 0
✅ ward_no nulls filled: 0

=== Nulls after Category 2 ===
police_station_m      695
ring_road_m           673
college_m             637
bhatbhateni_m         535
pharmacy_m            534
built_up_sqft         467
school_m              381
house_age             367
boudhanath_m          347
pashupatinath_m       284
hospital_m            281
public_transport_m    266
airport_m             248
property_face          99
road_width_feet         7
land_size_aana          1
dtype: int64

C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\lib\_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

In [48]:
from sklearn.impute import KNNImputer

In [49]:
# ─────────────────────────────────────────
# CATEGORY 4 — GROUPED MEDIAN IMPUTATION
# How it works: Instead of filling with global median
# we group by neighborhood first and use that group's median
# Why: A missing road width in Baluwatar is likely 16-20ft
# but in a rural area it might be 10ft
# Neighborhood-level median captures this local difference
# Example:
#   road_width_feet missing for a property in "Imadol"
#   All other "Imadol" properties have road_width median=13ft
#   → fill with 13ft ✅ much more accurate than global 15.5ft
# ─────────────────────────────────────────

# property_face — neighborhood mode then global mode
# Why mode not median: property_face is categorical not numeric
# Most common facing direction in a neighborhood is best guess
df_lph['property_face'] = df_lph.groupby('neighborhood')['property_face']\
    .transform(lambda x: x.fillna(x.mode()[0] if len(x.mode()) > 0 else np.nan))
df_lph['property_face'] = df_lph['property_face']\
    .fillna(df_lph['property_face'].mode()[0])
print(f"✅ property_face filled: {df_lph['property_face'].isnull().sum()} nulls remaining")

# road_width_feet — neighborhood median then global median
df_lph['road_width_feet'] = df_lph.groupby('neighborhood')['road_width_feet']\
    .transform(lambda x: x.fillna(x.median()))
df_lph['road_width_feet'] = df_lph['road_width_feet']\
    .fillna(df_lph['road_width_feet'].median())
print(f"✅ road_width_feet filled: {df_lph['road_width_feet'].isnull().sum()} nulls remaining")

# land_size_aana — neighborhood median then global median
df_lph['land_size_aana'] = df_lph.groupby('neighborhood')['land_size_aana']\
    .transform(lambda x: x.fillna(x.median()))
df_lph['land_size_aana'] = df_lph['land_size_aana']\
    .fillna(df_lph['land_size_aana'].median())
print(f"✅ land_size_aana filled: {df_lph['land_size_aana'].isnull().sum()} nulls remaining")

✅ property_face filled: 0 nulls remaining
✅ road_width_feet filled: 0 nulls remaining
✅ land_size_aana filled: 0 nulls remaining

In [50]:
# CATEGORY 5 — GROUPED MEDIAN IMPUTATION


# built_up_sqft — neighborhood + land_size bin grouped median
# Why both: Built up area depends on plot size AND location
# A 4 aana plot in Baluwatar has different built up than 4 aana in Bhaktapur
# Example:
#   Missing built_up_sqft for 4 aana plot in "Imadol"
#   Other "Imadol" + "small plot" properties have median=1026 sqft
#   → fill with 1026 sqft ✅ more accurate than global 1197 sqft
df_lph['land_size_bin'] = pd.cut(df_lph['land_size_aana'],
                                  bins=[0, 3, 5, 8, 15, 100],
                                  labels=['tiny', 'small', 'medium', 'large', 'xlarge'])
df_lph['built_up_sqft'] = df_lph.groupby(['neighborhood', 'land_size_bin'])['built_up_sqft']\
    .transform(lambda x: x.fillna(x.median()))
df_lph['built_up_sqft'] = df_lph.groupby('neighborhood')['built_up_sqft']\
    .transform(lambda x: x.fillna(x.median()))
df_lph['built_up_sqft'] = df_lph['built_up_sqft']\
    .fillna(df_lph['built_up_sqft'].median())
df_lph.drop(columns=['land_size_bin'], inplace=True)
print(f"✅ built_up_sqft filled: {df_lph['built_up_sqft'].isnull().sum()} nulls remaining")

C:\Users\DELL\AppData\Local\Temp\ipykernel_13424\2486033436.py:14: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_lph['built_up_sqft'] = df_lph.groupby(['neighborhood', 'land_size_bin'])['built_up_sqft']\
C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\lib\_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\lib\_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\lib\_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\lib\_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\lib\_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\lib\_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\lib\_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\lib\_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\lib\_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\lib\_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\lib\_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\lib\_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\lib\_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\lib\_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\lib\_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\lib\_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\lib\_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\lib\_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\lib\_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\lib\_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\lib\_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\lib\_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\lib\_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\lib\_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\lib\_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\lib\_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\lib\_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\lib\_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\lib\_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\lib\_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\lib\_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\lib\_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\lib\_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\lib\_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\lib\_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\lib\_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

✅ built_up_sqft filled: 0 nulls remaining

C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\lib\_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\lib\_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\lib\_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\lib\_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\lib\_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\lib\_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\lib\_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\lib\_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\lib\_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\lib\_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\lib\_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\lib\_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

In [51]:
# ─────────────────────────────────────────
# CATEGORY 6 — TEMPORAL IMPUTATION
# How it works: Newer neighborhoods have newer houses
# Using neighborhood median year is more accurate
# than global median because construction boomed
# in different areas at different times
# Example:
#   Anamnaagr (Kathmandu) — mostly older houses, median age=12
#   Imadol (Lalitpur) — newer development, median age=3
#   → fill missing house_age using neighborhood median
#   → much better than global median of 7.8 years
# ─────────────────────────────────────────
df_lph['house_age'] = df_lph.groupby('neighborhood')['house_age']\
    .transform(lambda x: x.fillna(x.median()))
df_lph['house_age'] = df_lph['house_age']\
    .fillna(df_lph['house_age'].median())
print(f"✅ house_age filled: {df_lph['house_age'].isnull().sum()} nulls remaining")

C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\lib\_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\lib\_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\lib\_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

✅ house_age filled: 0 nulls remaining

C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\lib\_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\lib\_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\lib\_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\lib\_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\lib\_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\lib\_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

In [52]:
# ─────────────────────────────────────────
# CATEGORY 5 — KNN IMPUTATION FOR DISTANCES
# How it works:
# KNN = K-Nearest Neighbors
# Step 1: Look at all distance columns together
# Step 2: For a row with missing hospital_m,
#         find K=5 most similar rows based on
#         OTHER distance values that ARE present
# Step 3: Use average of those 5 rows' hospital_m
#         as the imputed value
#
# Why KNN for distances:
# Properties near each other share similar distances
# to landmarks — if two properties have similar
# airport_m and ring_road_m, they probably also have
# similar hospital_m even if one is missing
#
# Example:
#   Property A: airport_m=5000, ring_road_m=2000, hospital_m=NaN
#   5 most similar properties (by airport+ring_road) have:
#   hospital_m = [800, 900, 750, 1000, 850]
#   → imputed hospital_m = mean(800,900,750,1000,850) = 860m ✅
#   Much better than global median of 1000m
#
# n_neighbors=5: use 5 most similar properties
# More neighbors = smoother but less local
# Fewer neighbors = more local but noisier
# 5 is a good balance for this dataset size
# ─────────────────────────────────────────
dist_knn_cols = ['hospital_m', 'airport_m', 'pharmacy_m', 'bhatbhateni_m',
                 'school_m', 'college_m', 'public_transport_m', 'police_station_m',
                 'pashupatinath_m', 'boudhanath_m', 'ring_road_m']

knn_imputer = KNNImputer(n_neighbors=5)

# KNN works on numeric data only
# It finds similarity based on non-null values in the row
# then uses those similar rows to estimate missing values
df_lph[dist_knn_cols] = knn_imputer.fit_transform(df_lph[dist_knn_cols])
print(f"✅ Distance columns KNN imputed")
for col in dist_knn_cols:
    print(f"   {col}: {df_lph[col].isnull().sum()} nulls remaining")

✅ Distance columns KNN imputed
   hospital_m: 0 nulls remaining
   airport_m: 0 nulls remaining
   pharmacy_m: 0 nulls remaining
   bhatbhateni_m: 0 nulls remaining
   school_m: 0 nulls remaining
   college_m: 0 nulls remaining
   public_transport_m: 0 nulls remaining
   police_station_m: 0 nulls remaining
   pashupatinath_m: 0 nulls remaining
   boudhanath_m: 0 nulls remaining
   ring_road_m: 0 nulls remaining

In [53]:
# ─────────────────────────────────────────
# FINAL VERIFY
# ─────────────────────────────────────────
print(f"\n=== Final null check ===")
nulls = df_lph.isnull().sum()
print(nulls[nulls > 0] if nulls[nulls > 0].any() else "✅ Zero nulls remaining")
print(f"\nFinal shape: {df_lph.shape}")

=== Final null check ===
✅ Zero nulls remaining

Final shape: (2190, 28)

In [54]:
df_lph['total_price'].isnull().sum()

np.int64(0)

In [55]:
df=df_lph.copy()

In [56]:
df.sample(10)

,district,property_type,property_face,road_type,negotiable,furnishing,property_area,date_posted,views,municipality,ward_no,neighborhood,total_price,land_size_aana,built_up_sqft,house_age,road_width_feet,hospital_m,airport_m,pharmacy_m,bhatbhateni_m,school_m,college_m,public_transport_m,police_station_m,pashupatinath_m,boudhanath_m,ring_road_m
1088,Kathmandu,Residential,South,High Access,Yes,Unfurnished,6 Aana,2024 November 28,290.0,Kathmandu,4.0,Baluwatar,70000000.0,6.00,1197.88,14.0,16.0,500.0,4000.0,500.0,1000.0,500.0,500.0,500.0,500.0,4000.0,6000.0,1000.0
2037,Bhaktapur,Residential,North-West,Low Access,Yes,Semi Furnished,3 Aana,2025 July 23,244.0,Changunarayan,8.0,Sudal,19000000.0,3.00,2016.78,1.0,13.0,3100.0,16000.0,3000.0,8100.0,2000.0,3000.0,500.0,2000.0,18000.0,17400.0,20000.0
186,Kathmandu,Commercial,North-East,High Access,Yes,Unfurnished,3.5 Aana,2025 August 5,144.0,Budanilkantha,10.0,Kapan,40000000.0,3.50,3100.00,17.0,26.0,1000.0,5000.0,0.0,1230.0,100.0,370.0,0.0,794.0,4000.0,4500.0,1640.0
531,Kathmandu,Residential,North,High Access,Yes,Semi Furnished,8 Aana,2025 May 4,254.0,Budhaknilkantha,1.0,Budhanilkantha,49500000.0,8.00,1369.00,8.0,20.0,1150.0,7180.0,360.0,1960.0,800.0,820.0,840.0,750.0,7000.0,11600.0,2200.0
1403,Kathmandu,Residential,South-East,High Access,Yes,Full Furnished,6 Aana,2024 August 14,211.0,Budhanilkantha,8.0,Budhanilkantha,65000000.0,6.00,3200.00,3.0,13.0,2000.0,8000.0,5.0,4000.0,5.0,5.0,5.0,15.0,6000.0,5000.0,1070.0
858,Kathmandu,Residential,North,High Access,Yes,Semi Furnished,6 Aana,2025 January 15,182.0,Budhanilkantha,7.0,Budhanilkantha,60000000.0,6.00,1369.00,3.0,13.0,1500.0,9100.0,200.0,2000.0,200.0,200.0,200.0,200.0,9700.0,6000.0,2000.0
1471,Kathmandu,Residential,South-East,High Access,Yes,Semi Furnished,1 Ropani,2024 August 5,460.0,Budhanilkantha,8.0,Budhanilkantha,140000000.0,16.00,2053.50,2.0,16.0,2000.0,7000.0,281.0,4000.0,321.0,271.0,321.0,283.0,6000.0,5000.0,2400.0
937,Kathmandu,Residential,East,High Access,Yes,Semi Furnished,3.75 Aana,2024 December 28,370.0,Kathmandu,14.0,Kalanki,33000000.0,3.75,1112.31,4.0,13.0,500.0,6000.0,300.0,1000.0,220.2,320.0,300.0,264.0,8000.0,9000.0,2310.0
1728,Lalitpur,Residential,South-West,High Access,Yes,Unfurnished,12 Aana,2025 March 6,495.0,Lalitpur,2.0,Manbhawan,20000000.0,12.00,2395.75,22.0,10.0,500.0,7000.0,300.0,1000.0,500.0,500.0,500.0,500.0,7000.0,7000.0,1000.0
168,Kathmandu,Residential,South-West,Low Access,Yes,Semi Furnished,2.87 Aana,2025 August 7,457.0,Budhanilkatha,13.0,Budhanilkantha,23000000.0,2.87,1026.75,1.0,12.0,200.0,7000.0,200.0,2500.0,200.0,200.0,200.0,200.0,6700.0,6700.0,2500.0

In [57]:
df.describe()

,views,ward_no,total_price,land_size_aana,built_up_sqft,house_age,road_width_feet,hospital_m,airport_m,pharmacy_m,bhatbhateni_m,school_m,college_m,public_transport_m,police_station_m,pashupatinath_m,boudhanath_m,ring_road_m
count,2190.000000,2190.000000,2.190000e+03,2190.000000,2190.000000,2190.000000,2190.000000,2190.000000,2190.000000,2190.000000,2190.000000,2190.000000,2190.000000,2190.00000,2190.000000,2190.000000,2190.000000,2190.000000
mean,377.847945,9.290411,4.317799e+07,5.244622,1456.852072,8.092466,15.540320,1031.807723,6437.894596,236.667816,1943.156696,346.057342,643.846440,246.25264,586.779938,6886.314849,7770.781706,2524.375485
std,268.437200,7.844576,3.233398e+07,6.454168,838.983794,8.558389,6.623584,960.459833,2892.551710,310.021493,1517.770677,421.222506,766.531036,236.64596,530.277513,3396.916506,4275.257432,2374.668740
min,81.000000,1.000000,1.000000e+07,0.000000,2.500000,0.000000,3.000000,0.000000,8.500000,0.000000,1.000000,0.000000,5.000000,0.00000,1.500000,3.800000,1.000000,0.000000
25%,225.250000,4.000000,2.600000e+07,3.250000,1026.750000,2.000000,13.000000,400.000000,4000.000000,100.000000,1000.000000,100.000000,200.000000,100.00000,300.000000,4500.000000,4500.000000,1000.000000
50%,312.000000,7.000000,3.500000e+07,4.000000,1197.880000,5.000000,13.000000,900.000000,6411.389547,200.000000,1860.000000,290.000000,420.000000,200.00000,500.000000,6877.741081,7000.000000,2000.000000
75%,444.000000,11.000000,4.800000e+07,5.500000,1711.250000,11.000000,20.000000,1047.724777,8000.000000,300.000000,2500.000000,400.000000,676.336768,300.00000,622.313043,9000.000000,11000.000000,3170.000000
max,3957.000000,35.000000,3.500000e+08,216.000000,10000.000000,61.000000,100.000000,8500.000000,19000.000000,10000.000000,12000.000000,8700.000000,8700.000000,3700.00000,5200.000000,21000.000000,30000.000000,25000.000000

In [59]:
# ─────────────────────────────────────────
# FINAL CHECKS
# ─────────────────────────────────────────

# Check 1 — Price range
print("=== total_price check ===")
print(df_lph['total_price'].describe())
print(f"Below 10M:  {(df_lph['total_price'] < 10000000).sum()}")
print(f"Above 350M: {(df_lph['total_price'] > 350000000).sum()}")

# Check 2 — Land size
print("\n=== land_size_aana check ===")
print(f"Below 1 aana:  {(df_lph['land_size_aana'] < 1).sum()}")
print(f"Above 50 aana: {(df_lph['land_size_aana'] > 50).sum()}")
print(df_lph['land_size_aana'].describe())

# Check 3 — Built up area
print("\n=== built_up_sqft check ===")
print(f"Below 100 sqft:   {(df_lph['built_up_sqft'] < 100).sum()}")
print(f"Above 15000 sqft: {(df_lph['built_up_sqft'] > 15000).sum()}")
print(df_lph['built_up_sqft'].describe())

# Check 4 — House age
print("\n=== house_age check ===")
print(f"Negative age: {(df_lph['house_age'] < 0).sum()}")
print(f"Above 60:     {(df_lph['house_age'] > 60).sum()}")
print(df_lph['house_age'].describe())

# Check 5 — Road width
print("\n=== road_width_feet check ===")
print(f"Above 80 feet: {(df_lph['road_width_feet'] > 80).sum()}")
print(df_lph['road_width_feet'].describe())

# Check 6 — Duplicates
print(f"\n=== Duplicates ===")
print(f"Duplicate rows: {df_lph.duplicated().sum()}")

# Check 7 — Categorical distributions
print("\n=== Categorical distributions ===")
for col in ['district', 'property_type', 'furnishing', 'road_type', 'property_face']:
    print(f"\n{col}:")
    print(df_lph[col].value_counts())

=== total_price check ===
count    2.190000e+03
mean     4.317799e+07
std      3.233398e+07
min      1.000000e+07
25%      2.600000e+07
50%      3.500000e+07
75%      4.800000e+07
max      3.500000e+08
Name: total_price, dtype: float64
Below 10M:  0
Above 350M: 0

=== land_size_aana check ===
Below 1 aana:  19
Above 50 aana: 4
count    2190.000000
mean        5.244622
std         6.454168
min         0.000000
25%         3.250000
50%         4.000000
75%         5.500000
max       216.000000
Name: land_size_aana, dtype: float64

=== built_up_sqft check ===
Below 100 sqft:   8
Above 15000 sqft: 0
count     2190.000000
mean      1456.852072
std        838.983794
min          2.500000
25%       1026.750000
50%       1197.880000
75%       1711.250000
max      10000.000000
Name: built_up_sqft, dtype: float64

=== house_age check ===
Negative age: 0
Above 60:     1
count    2190.000000
mean        8.092466
std         8.558389
min         0.000000
25%         2.000000
50%         5.000000
75%        11.000000
max        61.000000
Name: house_age, dtype: float64

=== road_width_feet check ===
Above 80 feet: 2
count    2190.000000
mean       15.540320
std         6.623584
min         3.000000
25%        13.000000
50%        13.000000
75%        20.000000
max       100.000000
Name: road_width_feet, dtype: float64

=== Duplicates ===
Duplicate rows: 0

=== Categorical distributions ===

district:
district
Kathmandu    1490
Lalitpur      525
Bhaktapur     175
Name: count, dtype: int64

property_type:
property_type
Residential        1876
Commercial          190
Semi-commercial     124
Name: count, dtype: int64

furnishing:
furnishing
Semi Furnished    1077
Unfurnished        792
Full Furnished     321
Name: count, dtype: int64

road_type:
road_type
High Access    1655
Low Access      535
Name: count, dtype: int64

property_face:
property_face
East          527
South         332
West          312
South-East    282
North-East    225
North         219
South-West    164
North-West    124
west            2
east            1
south-west      1
south-east      1
Name: count, dtype: int64

In [60]:
# ─────────────────────────────────────────
# FIX REMAINING ISSUES
# ─────────────────────────────────────────

# Fix 1 — property_face lowercase duplicates
# Why: "west" and "West" are same direction
# but model treats them as different categories
# Title case standardizes all values
df_lph['property_face'] = df_lph['property_face'].str.title()
print("=== property_face after fixing ===")
print(df_lph['property_face'].value_counts())

# Fix 2 — land_size_aana
# Cap minimum at 1 aana — smallest realistic residential plot
# Cap maximum at 50 aana — consistent with lalpurja land model
# Why 1 minimum: 0 aana means no land — impossible for a house
df_lph['land_size_aana'] = df_lph['land_size_aana'].clip(lower=1, upper=50)
print(f"\n✅ land_size_aana clipped: min={df_lph['land_size_aana'].min()}, max={df_lph['land_size_aana'].max()}")

# Fix 3 — built_up_sqft
# Replace values below 100 sqft with neighborhood median
# Why: 2.5 sqft is impossible for a house — clearly wrong
# Using neighborhood median preserves local building patterns
mask = df_lph['built_up_sqft'] < 100
df_lph.loc[mask, 'built_up_sqft'] = df_lph.loc[mask, 'neighborhood']\
    .map(df_lph.groupby('neighborhood')['built_up_sqft']\
    .apply(lambda x: x[x >= 100].median()))
# Fill any remaining with global median
df_lph['built_up_sqft'] = df_lph['built_up_sqft']\
    .fillna(df_lph['built_up_sqft'].median())
print(f"✅ built_up_sqft fixed: min={df_lph['built_up_sqft'].min():.1f}, max={df_lph['built_up_sqft'].max():.1f}")

# Fix 4 — house_age cap at 60
# Why: 61 year old house is suspicious in Kathmandu
# Most older houses have been rebuilt
# Cap at 60 to remove extreme outlier
df_lph['house_age'] = df_lph['house_age'].clip(upper=60)
print(f"✅ house_age capped: max={df_lph['house_age'].max()}")

# Fix 5 — road_width_feet cap at 80 feet
# Why: 100 feet road is extreme for residential areas
# Cap at 80 feet — realistic maximum for urban Nepal
df_lph['road_width_feet'] = df_lph['road_width_feet'].clip(upper=80)
print(f"✅ road_width_feet capped: max={df_lph['road_width_feet'].max()}")

# ─────────────────────────────────────────
# FINAL VERIFY
# ─────────────────────────────────────────
print(f"\n=== Final shape: {df_lph.shape} ===")
print(f"Nulls: {df_lph.isnull().sum().sum()}")
print(f"Duplicates: {df_lph.duplicated().sum()}")
print(f"price range: {df_lph['total_price'].min():,.0f} – {df_lph['total_price'].max():,.0f}")
print(f"land range: {df_lph['land_size_aana'].min()} – {df_lph['land_size_aana'].max()} aana")
print(f"built_up range: {df_lph['built_up_sqft'].min():.0f} – {df_lph['built_up_sqft'].max():.0f} sqft")

=== property_face after fixing ===
property_face
East          528
South         332
West          314
South-East    283
North-East    225
North         219
South-West    165
North-West    124
Name: count, dtype: int64

✅ land_size_aana clipped: min=1.0, max=50.0
✅ built_up_sqft fixed: min=119.2, max=10000.0
✅ house_age capped: max=60.0
✅ road_width_feet capped: max=80.0

=== Final shape: (2190, 28) ===
Nulls: 0
Duplicates: 0
price range: 10,000,000 – 350,000,000
land range: 1.0 – 50.0 aana
built_up range: 119 – 10000 sqft

In [61]:
# ─────────────────────────────────────────
# SAVE CLEANED LALPURJA HOUSING DATASET
# All cleaning completed:
# - 138 suspicious price rows removed
# - total_price parsed from "3 Crore 50 Lakh" → NPR
# - land_size_aana parsed from all units (aana/ropani/sqft)
# - built_up_sqft parsed and fixed
# - house_age calculated from year_built (BS/AD handled)
# - road_width_feet parsed (feet/meters handled)
# - Distance columns converted to meters and KNN imputed
# - Municipality standardization pending (will do in EDA)
# - Neighborhood cleaning pending (will do in EDA)
# - Zero nulls, zero duplicates
# ─────────────────────────────────────────
df_lph.to_csv('cleaned_lalpurja_house_after_cleaning.csv', index=False)

print(f"✅ Saved cleaned_lalpurja_house_after_cleaning.csv")
print(f"✅ Shape: {df_lph.shape}")
print(f"✅ Nulls: {df_lph.isnull().sum().sum()}")
print(f"✅ Columns: {list(df_lph.columns)}")

✅ Saved cleaned_lalpurja_house_after_cleaning.csv
✅ Shape: (2190, 28)
✅ Nulls: 0
✅ Columns: ['district', 'property_type', 'property_face', 'road_type', 'negotiable', 'furnishing', 'property_area', 'date_posted', 'views', 'municipality', 'ward_no', 'neighborhood', 'total_price', 'land_size_aana', 'built_up_sqft', 'house_age', 'road_width_feet', 'hospital_m', 'airport_m', 'pharmacy_m', 'bhatbhateni_m', 'school_m', 'college_m', 'public_transport_m', 'police_station_m', 'pashupatinath_m', 'boudhanath_m', 'ring_road_m']

In [62]:
# ─────────────────────────────────────────
# COLUMN DESCRIPTIONS — LALPURJA HOUSING DATASET
# ─────────────────────────────────────────

# ── LOCATION COLUMNS ───────────────────────────────────────────────────────

# district
# Which of the 3 Kathmandu valley districts the property is in
# Values: Kathmandu (1490), Lalitpur (525), Bhaktapur (175)
# Example: "Kathmandu"

# municipality
# Local government body the property falls under
# More granular than district — captures micro-market differences
# Example: "Budhanilkantha", "Mahalaxmi", "Suryabinayak"
# Filled using neighborhood-level mode (Category 2 imputation)

# ward_no
# Ward number within the municipality (1–33)
# Most granular location identifier available
# Example: Ward 3 of Mahalaxmi municipality = Imadol area
# Filled using neighborhood-level mode (Category 2 imputation)

# neighborhood
# Neighborhood name extracted from listing
# Key price signal — location within ward level
# Example: "Imadol", "Budhanilkantha", "Balkot"
# Only 2 nulls — filled with district mode

# ── PROPERTY CHARACTERISTICS ───────────────────────────────────────────────

# property_type
# Land use classification of the property
# Values: Residential (1876), Commercial (190), Semi-commercial (124)
# Example: "Residential"

# property_face
# Cardinal direction the property faces
# Values: East (528), South (332), West (314), South-East (283) etc.
# Standardized to title case — "west" → "West"
# Vastu shastra affects buyer preference in Nepal
# Example: "East" facing is most preferred

# furnishing
# Furniture status of the property
# Values: Semi Furnished (1077), Unfurnished (792), Full Furnished (321)
# NaN filled with "Unfurnished" — conservative default for Nepal market
# Example: "Semi Furnished"

# road_type
# Quality of road accessing the property
# Values: High Access (1655) = Blacktopped/Paved
#         Low Access (535)  = Gravelled/Soil/Alley
# NaN filled with "High Access" — most common in urban Nepal
# Example: "High Access"

# negotiable
# Whether the listed price is open to negotiation
# Values: Yes (2155), No (35)
# 98.4% are Yes — NaN filled with "Yes" (Nepal market standard)
# Example: "Yes"

# ── SIZE COLUMNS ───────────────────────────────────────────────────────────

# land_size_aana
# Size of the plot/land in aana (1 aana ≈ 31.8 sqm)
# Parsed from property_area — handled aana/ropani/sqft/paisa/daam units
# Clipped: min=1 aana, max=50 aana
# Example: "4 Aana" → 4.0

# built_up_sqft
# Built up area of the house in square feet
# Parsed from built_up_area — handled sqft/aana/sqm units
# Mislabeled aana values (>50) treated as sqft
# Example: "1369 square-feet" → 1369.0
#          "3 aana" → 3 × 342.25 = 1026.75 sqft

# house_age
# Age of the house in years (current_year - year_built)
# Calculated dynamically using datetime.now().year
# BS calendar years converted to AD (subtract 56)
# Example: year_built=2079 BS → 2023 AD → age=3 years
# Filled with neighborhood median (newer areas = newer houses)

# road_width_feet
# Width of the road accessing the property in feet
# Parsed from road_access — handled feet and meter units
# "20 Meter" → 20 × 3.281 = 65.62 feet
# Capped at 80 feet maximum
# Example: "13 Feet" → 13.0

# ── LISTING METADATA ───────────────────────────────────────────────────────

# property_area
# Original raw land size string — kept for reference
# Already parsed into land_size_aana
# Example: "4 Aana", "1 Ropani", "2000 Sq. Ft."
# Will be dropped before modeling

# date_posted
# Date the listing was posted on lalpurja.com
# Format: "2025 November 8"
# Not used for modeling — kept for reference
# Will be dropped before modeling

# views
# Number of times the listing was viewed on lalpurja.com
# Near-zero correlation with price (confirmed in lalpurja land EDA)
# Will likely be dropped before modeling

# ── TARGET VARIABLE ────────────────────────────────────────────────────────

# total_price
# Total asking price of the property in NPR
# Parsed from total_price_raw — "3 Crore 50 Lakh" → 35,000,000 NPR
# Range: 10,000,000 (1 Crore) to 350,000,000 (35 Crore)
# This is the TARGET variable for regression modeling

# ── AMENITY DISTANCE COLUMNS (all in meters) ───────────────────────────────

# hospital_m
# Distance to nearest hospital in meters
# Capped at 15,000m — KNN imputed for nulls
# Example: "1km" → 1000m, "500m" → 500m

# airport_m
# Distance to Tribhuvan International Airport in meters
# Strong price predictor — closer to airport = more urban = higher price
# Capped at 30,000m — KNN imputed for nulls
# Example: "6km" → 6000m

# pharmacy_m
# Distance to nearest pharmacy in meters
# Proxy for urban infrastructure density
# Capped at 10,000m — KNN imputed for nulls

# bhatbhateni_m
# Distance to nearest Bhatbhateni Supermarket in meters
# Major landmark supermarket chain — proxy for urban amenity access
# Capped at 15,000m — KNN imputed for nulls

# school_m
# Distance to nearest school in meters
# Important for families — affects residential demand
# Capped at 10,000m — KNN imputed for nulls

# college_m
# Distance to nearest college in meters
# More relevant for semi-commercial and rental properties
# Capped at 15,000m — KNN imputed for nulls
# Had 29% nulls — higher than other amenities

# public_transport_m
# Distance to nearest public transport stop in meters
# Bus stop, microbus stand — measures daily commute convenience
# Capped at 5,000m — KNN imputed for nulls

# police_station_m
# Distance to nearest police station in meters
# Proxy for safety and urban infrastructure
# Had 31.7% nulls — highest among kept amenity columns
# Capped at 15,000m — KNN imputed for nulls

# pashupatinath_m
# Distance to Pashupatinath Temple in meters
# Major geographic landmark — captures centrality within valley
# Capped at 30,000m — KNN imputed for nulls

# boudhanath_m
# Distance to Boudhanath Stupa in meters
# Major geographic landmark — reference point for east Kathmandu
# Capped at 30,000m — KNN imputed for nulls

# ring_road_m
# Distance to Kathmandu Ring Road in meters
# Strong price predictor — ring road proximity = urban = higher price
# Had 30.7% nulls — KNN imputed using spatial similarity
# Capped at 30,000m
# Example: "2km" → 2000m